from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from voidscreen.sigma_v6_ctp_action import (
    advanced_impulse_response,
    constraint_pair_kinetic_hessian,
    kinetic_signature,
    localized_initial_data_count,
    retarded_impulse_response,
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit the v6D CTP action localization.")
    parser.add_argument(
        "--config",
        type=Path,
        default=ROOT / "configs" / "sigma_v6d_ctp_action_gate.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "results" / "sigma_v6d_ctp_action_gate",
    )
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    counts = [int(value) for value in config["component_counts_for_constraint_pairs"]]
    hessian = constraint_pair_kinetic_hessian(counts, float(config["kinetic_mixing"]))
    signature = kinetic_signature(hessian)
    initial_data = localized_initial_data_count(counts)

    causal = config["causal_support_audit"]
    time = np.linspace(
        float(causal["time_min"]),
        float(causal["time_max"]),
        int(causal["samples"]),
    )
    impulse_time = float(causal["impulse_time"])
    frequency = float(causal["frequency"])
    retarded = retarded_impulse_response(time, impulse_time, frequency)
    advanced = advanced_impulse_response(time, impulse_time, frequency)
    retarded_pre_support = float(np.max(np.abs(retarded[time < impulse_time])))
    advanced_post_support = float(np.max(np.abs(advanced[time > impulse_time])))
    advanced_pre_response = float(np.max(np.abs(advanced[time < impulse_time])))

    thresholds = config["gates"]
    formal_ward_identity = True
    minimal_matter_conservation = True
    gates = {
        "closed_time_path_retarded_support_can_be_imposed": retarded_pre_support
        <= float(thresholds["maximum_forbidden_causal_support"]),
        "advanced_adjoint_support_is_distinct": advanced_post_support
        <= float(thresholds["maximum_forbidden_causal_support"])
        and advanced_pre_response > 0.0,
        "diagonal_diffeomorphism_Ward_identity": formal_ward_identity,
        "minimal_matter_conservation": minimal_matter_conservation,
        "positive_localized_kinetic_matrix": int(signature["negative"])
        <= int(thresholds["maximum_negative_kinetic_directions"]),
        "no_extra_free_multiplier_components": int(
            initial_data["extra_multiplier_configuration_components"]
        )
        <= int(thresholds["maximum_extra_free_multiplier_components"]),
        "parameter_count": int(config["physical_parameters"]["count"])
        <= int(config["physical_parameters"]["maximum_allowed"]),
    }
    gates = {name: bool(value) for name, value in gates.items()}
    report = {
        "status": "completed Sigma v6D closed-time-path action gate",
        "observational_data_accessed": False,
        "raw_holdout_opened": False,
        "action": {
            "localized_branch_action": config["localized_branch_action"],
            "closed_time_path": config["closed_time_path"],
            "physical_metric_count": int(config["branch_fields"]["physical_metric"]),
            "physical_parameter_count": int(config["physical_parameters"]["count"]),
        },
        "ward_identity": {
            "formula": "-2 nabla_mu E_g^mu_nu + E_U nabla_nu U + E_A nabla_nu A + E_Q^ab nabla_nu Q_ab - 2 nabla_a(E_Q^ab Q_nu_b) + E_B^ab nabla_nu B_ab - 2 nabla_a(E_B^ab B_nu_b) = 0",
            "on_shell_consequence": "nabla_mu E_g^mu_nu=0 on every auxiliary equation; diagonal branch invariance gives the physical CTP identity after g_plus=g_minus",
            "initial_state_condition": "the initial density functional and final branch matching must be invariant under the diagonal diffeomorphism",
            "minimal_matter_consequence": "nabla_mu T_b^mu_nu=0 on the baryonic matter equations",
            "passes_formally": formal_ward_identity and minimal_matter_conservation,
        },
        "causal_support": {
            "maximum_retarded_pre_impulse_response": retarded_pre_support,
            "maximum_advanced_post_impulse_response": advanced_post_support,
            "maximum_advanced_pre_impulse_response": advanced_pre_response,
            "interpretation": "Retarded initial conditions make the response causal, while the adjoint multiplier generated by an ordinary endpoint variation has advanced support. The CTP contour can select the former only by treating the multipliers as response variables or physical fields with fixed state.",
        },
        "localized_kinetic_matrix": {
            "shape": list(hessian.shape),
            "eigenvalues": [float(value) for value in signature["eigenvalues"]],
            "positive_directions": int(signature["positive"]),
            "negative_directions": int(signature["negative"]),
            "null_directions": int(signature["null"]),
            "rank": int(signature["rank"]),
            "initial_data_count": initial_data,
            "interpretation": "Each A-U or B-Q constraint block has eigenvalues plus/minus |mixing|. Changing its overall sign only exchanges eigenvectors and cannot make the localization positive definite.",
        },
        "gates": gates,
        "all_fundamental_action_gates_pass": bool(all(gates.values())),
        "decision": "retire_v6D_as_fundamental_field_theory_retain_only_as_effective_response_control",
        "reason": "The covariant CTP construction can be formally conserved and causal, but its minimal variational localization contains six negative kinetic directions and six extra multiplier configurations. Declaring them fixed nonphysical auxiliaries recovers a phenomenological nonlocal response but does not satisfy the goal's positive-energy fundamental-action gate.",
        "scope": "This rejects the exact constraint-localized v6D action. It does not prove that every UV-complete causal nonlocal theory or every healthy local gravitational carrier is impossible.",
        "next_mechanism_requirement": "Any successor must generate the orientation response by integrating out a manifestly positive local carrier (with its state fixed universally), not by imposing inverse operators with Lagrange-multiplier pairs.",
        "data_policy": config["data_policy"],
    }
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "report.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
