#!/usr/bin/env python3
"""Write exact software/CCF locks and the RX J2129 XMM environment manifest."""

from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "configs/r1_rxj2129_xmm_environment_protocol.json"
ACQUISITION = ROOT / "results/r1_rxj2129_xmm_acquisition/report.json"
MANIFEST = ROOT / "data/derived/r1_rxj2129_xmm_environment_manifest.json"
EXPLICIT_LOCK = ROOT / "data/derived/r1_rxj2129_xmm_heasoft_explicit_lock.txt"
CONDA_META_LOCK = ROOT / "data/derived/r1_rxj2129_xmm_conda_meta_lock.json"
PIP_LOCK = ROOT / "data/derived/r1_rxj2129_xmm_pip_freeze.txt"


def run_wsl(arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["wsl.exe", "-d", "Ubuntu-24.04", "--", *arguments],
        capture_output=True,
        text=True,
        check=False,
    )


def require(result: subprocess.CompletedProcess[str], label: str) -> str:
    if result.returncode != 0:
        raise RuntimeError(f"{label} failed ({result.returncode}): {result.stderr}")
    return result.stdout


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def wsl_sha256(path: str) -> str:
    output = require(run_wsl(["sha256sum", path]), f"sha256 {path}")
    return output.split()[0].lower()


def main() -> None:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    acquisition = json.loads(ACQUISITION.read_text(encoding="utf-8"))
    paths = config["paths"]
    mamba = paths["mamba_executable"]
    heasoft = paths["heasoft_prefix"]
    ccf = paths["ccf_snapshot"]
    sas_archive = f"{paths['installer_directory']}/{config['sas']['archive_filename']}"

    explicit_raw = require(
        run_wsl([mamba, "list", "--explicit", "--prefix", heasoft]),
        "explicit conda lock",
    )
    packages_raw = require(
        run_wsl([mamba, "list", "--json", "--prefix", heasoft]),
        "conda package inventory",
    )
    packages = json.loads(packages_raw)
    conda_meta_code = (
        "import glob,json,pathlib; "
        f"p={heasoft!r}; "
        "rows=[json.load(open(x,encoding='utf-8')) for x in glob.glob(p+'/conda-meta/*.json')]; "
        "print(json.dumps(sorted(rows,key=lambda r:(r.get('name',''),r.get('version',''))),sort_keys=True))"
    )
    conda_meta = json.loads(
        require(
            run_wsl([f"{heasoft}/bin/python", "-c", conda_meta_code]),
            "conda metadata lock",
        )
    )
    pip_freeze_raw = require(
        run_wsl([f"{heasoft}/bin/python", "-m", "pip", "freeze", "--all"]),
        "pip freeze",
    )

    explicit_urls = sorted(
        line.strip()
        for line in explicit_raw.splitlines()
        if line.strip().startswith("https://")
    )
    if len(explicit_urls) != len(conda_meta):
        raise RuntimeError(
            f"explicit lock has {len(explicit_urls)} URLs for {len(conda_meta)} conda packages"
        )
    explicit = (
        "# RX J2129 XMM HEASoft 6.36 environment; generated by mamba list --explicit\n"
        "@EXPLICIT\n"
        + "\n".join(explicit_urls)
        + "\n"
    )
    pyds9_lines = [
        line.strip()
        for line in pip_freeze_raw.splitlines()
        if line.strip().lower().startswith("pyds9 @ ")
    ]
    if len(pyds9_lines) != 1:
        raise RuntimeError(f"expected one direct pyds9 pin, found {pyds9_lines}")
    pip_freeze = "# Packages installed outside conda\n" + pyds9_lines[0] + "\n"

    EXPLICIT_LOCK.parent.mkdir(parents=True, exist_ok=True)
    EXPLICIT_LOCK.write_text(explicit, encoding="utf-8")
    CONDA_META_LOCK.write_text(json.dumps(conda_meta, indent=2) + "\n", encoding="utf-8")
    PIP_LOCK.write_text(pip_freeze, encoding="utf-8")

    setup_script = (
        "/mnt/c/Users/henry/Documents/Codex/2026-07-18/"
        "sigmagravity-frontiers-main/research/galaxy-cluster-unification/"
        "scripts/setup_r1_rxj2129_xmm_environment.sh"
    )
    task_versions = run_wsl(["bash", setup_script, "versions"])
    task_tokens = [
        "SAS release: 22.1.0-a8f2c2afa-20250304",
        "26Sep2025_V6.36",
        "cifbuild (cifbuild-4.10.1)",
        "odfingest (odfingest-3.33.2)",
        "emproc (epicproc-2.25.4)",
        "epproc (epicproc-2.25.4)",
        "XSPEC version: 12.15.1",
        "SAS Python imports passed",
    ]
    task_output = task_versions.stdout + "\n" + task_versions.stderr
    task_gate = task_versions.returncode == 0 and all(
        token in task_output for token in task_tokens
    )

    ccf_verify = run_wsl(
        ["bash", "-lc", f"cd {ccf} && sha256sum -c --quiet CCF_MANIFEST.sha256"]
    )
    ccf_stats_code = (
        "from pathlib import Path; "
        f"p=Path({ccf!r}); "
        "f=list(p.glob('*.CCF')); print(len(f),sum(x.stat().st_size for x in f))"
    )
    ccf_stats = require(run_wsl(["python3", "-c", ccf_stats_code]), "CCF stats").split()
    ccf_files, ccf_bytes = map(int, ccf_stats)
    ccf_manifest_sha = wsl_sha256(f"{ccf}/CCF_MANIFEST.sha256")
    sas_archive_sha = wsl_sha256(sas_archive)
    sas_archive_bytes = int(
        require(run_wsl(["stat", "--printf=%s", sas_archive]), "SAS archive size")
    )
    ccf_gate = bool(
        ccf_verify.returncode == 0
        and ccf_files == 1815
        and ccf_bytes == 9260611200
        and ccf_manifest_sha
        == "c9898b72ccb2458b3598a4df267a218968d8b3c2ea902de890bcaed56c8cfa28"
    )
    sas_gate = bool(
        sas_archive_bytes == config["sas"]["archive_bytes"]
        and sas_archive_sha == config["sas"]["archive_sha256"]
    )
    package_by_name = {row["name"]: row for row in packages}
    package_gate = bool(
        package_by_name.get("heasoft", {}).get("version") == "6.36"
        and package_by_name.get("xspec-data", {}).get("version") == "6.36"
        and pyds9_lines[0].endswith(
            "#sha256=b4f198f5d29b749f721c491f8384f6293e43ec417bd0492be36bffb5c3904b2a"
        )
    )
    environment_gate = bool(
        acquisition["gates"]["R1B3_XMM_acquisition_gate_passed"]
        and sas_gate
        and package_gate
        and task_gate
        and ccf_gate
    )

    manifest = {
        "manifest_version": "R1B3-RXJ2129-XMM-environment-manifest-0.1",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "protocol_version": config["protocol_version"],
        "selection_blind": True,
        "obsid": config["obsid"],
        "XMM_pixels_inspected": False,
        "sas": {
            "archive_url": config["sas"]["official_url"],
            "archive_bytes": sas_archive_bytes,
            "archive_sha256": sas_archive_sha,
            "installed_prefix": paths["sas_prefix"],
            "task_version_check_exit_code": task_versions.returncode,
            "task_version_check_stdout": task_versions.stdout,
            "task_version_check_stderr": task_versions.stderr,
            "all_declared_task_versions_and_python_imports_passed": task_gate,
        },
        "heasoft": {
            "prefix": heasoft,
            "mamba_list_entries_including_pip": len(packages),
            "conda_package_count": len(conda_meta),
            "heasoft_version": package_by_name["heasoft"]["version"],
            "xspec_data_version": package_by_name["xspec-data"]["version"],
            "explicit_lock_path": str(EXPLICIT_LOCK.relative_to(ROOT)).replace("\\", "/"),
            "explicit_lock_sha256": sha256(EXPLICIT_LOCK),
            "conda_meta_lock_path": str(CONDA_META_LOCK.relative_to(ROOT)).replace("\\", "/"),
            "conda_meta_lock_sha256": sha256(CONDA_META_LOCK),
            "pip_lock_path": str(PIP_LOCK.relative_to(ROOT)).replace("\\", "/"),
            "pip_lock_sha256": sha256(PIP_LOCK),
            "pyds9_version": "1.8.1",
            "package_gate_passed": package_gate,
        },
        "ccf": {
            "source": config["ccf"]["source"],
            "snapshot_date_utc": config["ccf"]["snapshot_date_utc"],
            "analysis_date": config["ccf"]["analysis_date"],
            "constituent_files": ccf_files,
            "constituent_bytes": ccf_bytes,
            "manifest_sha256": ccf_manifest_sha,
            "all_constituent_hashes_reverified": ccf_verify.returncode == 0,
        },
        "gates": {
            "source_archive_checksum_passed": sas_gate,
            "HEASoft_XSPEC_and_python_packages_passed": package_gate,
            "all_version_and_import_commands_passed": task_gate,
            "dated_CCF_snapshot_and_hash_reverification_passed": ccf_gate,
            "R1B3_XMM_reduction_environment_gate_passed": environment_gate,
            "R1B3_XMM_event_processing_gate_passed": False,
        },
        "authorization": {
            "freeze_XMM_event_processing_commands": environment_gate,
            "run_cifbuild_or_odfingest": False,
            "inspect_XMM_event_arrays": False,
            "run_EPIC_reduction": False,
            "infer_gas_profile": False,
            "measure_HST_arc_pixels": False,
            "infer_dynamical_or_Weyl_response": False,
            "fit_new_force_or_action": False,
        },
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
