"""Candidate-bound deterministic-compensator admission gate for transaction counts."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

CONFIG_SCHEMA = "sigma-kastner-schlatter-deterministic-compensator-admission-config-1.0"
RESULT_SCHEMA = "sigma-kastner-schlatter-deterministic-compensator-admission-1.0"
FIRST_BLOCKER = (
    "no_registered_QED_probability_space_causal_filtration_or_deterministic_"
    "compensator_martingale_identity"
)
SECOND_BLOCKER = (
    "candidate_actions_define_positive_mean_intensity_but_do_not_select_between_"
    "Poisson_and_same_mean_Cox_completions"
)
PDF_SHA256 = "c2f671293d07b21397e745da00a3ce1a2193c00da647a2ebf4147612b76c1780"


def _canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _sha(value: Any) -> str:
    return hashlib.sha256(_canonical(value).encode()).hexdigest()


def _file_sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _content_sha(value: Mapping[str, Any]) -> str:
    return _sha({key: item for key, item in value.items() if key != "content_sha256"})


def _inside(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise ValueError("deterministic-compensator path escapes repository") from error
    return path


def _bound_artifact(root: Path, binding: Mapping[str, Any]) -> dict[str, Any]:
    if set(binding) != {"path", "file_sha256", "content_sha256"}:
        raise ValueError("deterministic-compensator predecessor binding shape changed")
    path = _inside(root, str(binding["path"]))
    if not path.is_file() or _file_sha(path) != binding["file_sha256"]:
        raise ValueError("deterministic-compensator predecessor file hash mismatch")
    value = json.loads(path.read_text(encoding="utf-8"))
    if (
        not isinstance(value, dict)
        or value.get("content_sha256") != binding["content_sha256"]
        or _content_sha(value) != binding["content_sha256"]
    ):
        raise ValueError("deterministic-compensator predecessor content hash mismatch")
    return value


def _validate_config(config: Mapping[str, Any]) -> None:
    if (
        set(config)
        != {
            "schema_version",
            "campaign_id",
            "output_path",
            "predecessors",
            "theorem_domain",
            "admission_policy",
            "seals",
        }
        or config.get("schema_version") != CONFIG_SCHEMA
    ):
        raise ValueError("deterministic-compensator config shape changed")
    if set(config.get("predecessors", {})) != {
        "qed_actualization_audit",
        "positive_reparameterization",
        "candidate_action_completion",
        "candidate_formal_admission",
        "conditional_poisson_kernel",
        "paper_intake",
        "equation_graph",
    }:
        raise ValueError("deterministic-compensator predecessor set changed")
    if config.get("theorem_domain") != {
        "spacetime": "regular globally hyperbolic patch with declared Cauchy time tau",
        "field_conditioning": "fixed finite-real phi and metric g on a relatively compact W",
        "candidate_intensity": "mu_g_phi(dx)=q0*exp(phi(x))*dVol_g(x), q0>0",
        "random_measure": "simple adapted nonexplosive integer-valued N on W",
        "filtration": "right-continuous complete F_t generated by actualizations plus declared initial data",
    }:
        raise ValueError("deterministic-compensator theorem domain changed")
    if config.get("admission_policy") != {
        "positive_scalar_field_counts_as_mean_measure_only": True,
        "deterministic_compensator_may_select_conditional_Poisson": True,
        "deterministic_action_implies_martingale_identity": False,
        "unconditional_mean_intensity_implies_deterministic_compensator": False,
        "candidate_action_rejection_allowed": False,
    }:
        raise ValueError("deterministic-compensator admission policy changed")
    if any(config.get("seals", {}).values()):
        raise ValueError("deterministic-compensator seal opened")


def _validate_predecessors(values: Mapping[str, Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    audit = values["qed_actualization_audit"]
    if (
        audit.get("decision_counts") != {"pass": 0, "reject": 0, "blocked": 2}
        or audit.get("first_blocker")
        != "no_registered_QED_actualization_channel_probability_array_or_predictable_hazard_kernel"
        or audit.get("gate_counts", {}).get("paper_or_QED_channel_kernels_registered") != 0
        or any(audit.get("claim_seals", {}).values())
        or any(audit.get("data_seals", {}).values())
    ):
        raise ValueError("QED actualization audit boundary changed")

    positive = values["positive_reparameterization"]
    records = positive.get("candidate_records", [])
    if (
        positive.get("decision_counts") != {"pass": 0, "reject": 0, "blocked": 2}
        or [record.get("branch_id") for record in records]
        != ["eq35_middle_h", "eq35_printed_planck"]
        or any(
            record.get("field_diffeomorphism", {}).get("map") != "q=q0*exp(phi)"
            for record in records
        )
        or any(
            record.get("gate_ledger", {}).get("action_derived_point_process_probability_measure")
            != "blocked"
            for record in records
        )
    ):
        raise ValueError("positive-reparameterization boundary changed")

    action = values["candidate_action_completion"]
    hypotheses = action.get("completion_hypotheses", [])
    if (
        [record.get("branch_id") for record in hypotheses]
        != ["eq35_middle_h", "eq35_printed_planck"]
        or any(
            record.get("candidate_action", {}).get("stochastic_law_derived_by_action")
            for record in hypotheses
        )
        or any(record.get("paper_authorship_or_derivation") for record in hypotheses)
    ):
        raise ValueError("candidate-action stochastic boundary changed")

    formal = values["candidate_formal_admission"]
    if (
        formal.get("decision_counts") != {"blocked": 2, "pass": 0, "reject": 0}
        or any(
            record.get("decision") != "blocked" for record in formal.get("candidate_records", [])
        )
        or any(formal.get("claim_seals", {}).values())
        or any(formal.get("data_seals", {}).values())
    ):
        raise ValueError("candidate formal-admission boundary changed")

    conditional = values["conditional_poisson_kernel"]
    if (
        conditional.get("gate_counts", {}).get("compiler_authored_conditional_kernels") != 2
        or conditional.get("gate_counts", {}).get("paper_or_QED_actualization_derivation_pass") != 0
    ):
        raise ValueError("conditional-Poisson kernel boundary changed")

    intake = values["paper_intake"]
    if intake.get("primary_source", {}).get("pdf_sha256") != PDF_SHA256:
        raise ValueError("paper source hash changed")
    graph = values["equation_graph"]
    nodes = graph.get("knowledge_graph", {}).get("nodes", [])
    node_ids = {node.get("node_id") for node in nodes}
    if not {"EQ-KS-33-FOUR-RATE", "ACTION-CONTRACT-ABSENT"}.issubset(node_ids):
        raise ValueError("paper equation/action graph boundary changed")
    return records


def _compensator_theorem() -> dict[str, Any]:
    return {
        "attribution": "compiler_authored_conditional_characterization_not_in_or_derived_by_the_paper",
        "premises": {
            "probability_space": "(Omega,F,P) with right-continuous complete filtration F_t",
            "causal_order": "declared Cauchy time tau on W",
            "random_measure": "simple adapted nonexplosive integer-valued N",
            "deterministic_measure": "mu(dx)=q0*exp(phi(x))*dVol_g(x), conditional on fixed (g,phi)",
            "compensator_identity": (
                "for every bounded predictable h, Integral h*(N-mu) is a martingale"
            ),
            "integrability": "mu(W)<infinity; localization extends to locally finite W",
        },
        "exponential_martingale": (
            "Z_t(f)=exp(-Integral_{W_t} f*dN+Integral_{W_t}(1-exp(-f))*dmu)"
        ),
        "conditional_Laplace_conclusion": (
            "E[exp(-Integral_{W_t\\W_s} f*dN)|F_s,g,phi]=exp(-Integral_{W_t\\W_s}(1-exp(-f))*dmu)"
        ),
        "consequences": [
            "conditional Poisson counts on every finite measurable partition",
            "independent increments relative to the declared filtration",
            "same conditional Laplace functional as the registered compiler kernel",
        ],
        "set_indexed_scope": (
            "all relatively compact measurable cells after a projectively consistent locally finite extension"
        ),
        "candidate_action_or_paper_supplies_compensator_identity": False,
    }


def _evidence_gap_ledger() -> list[dict[str, Any]]:
    return [
        {"obligation": "probability_space_for_actualizations", "status": "absent"},
        {"obligation": "causal_time_and_actualization_filtration", "status": "absent"},
        {"obligation": "adapted_simple_counting_random_measure", "status": "absent"},
        {"obligation": "QED_predictable_compensator_identity", "status": "absent"},
        {"obligation": "martingale_integrability_and_nonexplosion", "status": "absent"},
        {"obligation": "projectively_consistent_set_indexed_extension", "status": "absent"},
        {"obligation": "positive_candidate_mean_measure", "status": "closed_by_compiler_action"},
        {"obligation": "conditional_Poisson_kernel_formula", "status": "closed_by_compiler_kernel"},
        {"obligation": "paper_or_QED_derivation_of_compensator", "status": "absent"},
        {"obligation": "operational_event_to_actualization_filtration_bridge", "status": "absent"},
    ]


def _exact_controls() -> dict[str, Any]:
    return {
        "two_cell_Laplace_positive_control": {
            "mu": ["2", "3"],
            "f": ["log(2)", "log(3)"],
            "Laplace_functional": "exp(-3)",
            "factorized_cell_product": "exp(-3)",
            "pass": True,
        },
        "same_action_Poisson_Cox_nonidentifiability": {
            "shared_candidate_field": "q=q0*exp(phi)",
            "completion_A": "N|(g,phi)~PRM(mu_g_phi)",
            "completion_B": ("Z in {1/2,3/2} equiprobable; N|(g,phi,Z)~PRM(Z*mu_g_phi)"),
            "same_unconditional_mean_measure": True,
            "Poisson_variance_on_B": "mu_B",
            "Cox_variance_on_B": "mu_B+mu_B^2/4",
            "same_deterministic_candidate_action": True,
            "action_selects_between_completions": False,
        },
        "random_compensator_negative_control": {
            "Cox_compensator_given_Z": "Z*mu_g_phi",
            "unconditional_mean": "mu_g_phi",
            "deterministic_compensator_claim": False,
            "reason": "unconditional mean intensity is not the predictable compensator",
        },
        "action_variable_type_negative_control": {
            "registered_action_variables": ["g_mn", "q or phi"],
            "absent_variables": ["N", "Omega", "F_t", "P", "expectation", "martingale"],
            "variational_derivation_of_compensator_identity": False,
        },
        "paper_rate_negative_control": {
            "registered_paper_quantity": "constant average q_gamma per four-volume",
            "mutation": "identify q_gamma with a predictable compensator without a filtration",
            "rejected": True,
        },
    }


def _candidate_record(record: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "branch_id": record["branch_id"],
        "beta": record["beta"],
        "candidate_intensity": "mu_g_phi(dx)=q0*exp(phi(x))*dVol_g(x)",
        "positive_mean_measure_on_regular_finite_phi_patch": True,
        "compiler_compensator_theorem_interface": "pass",
        "action_registered_event_variables": False,
        "action_or_QED_compensator_identity_derived": False,
        "same_action_alternative_law_witness": True,
        "candidate_action_rejection_authorized": False,
        "candidate_decision": "blocked",
        "first_blocker": FIRST_BLOCKER,
    }


def _validate_result(result: Mapping[str, Any]) -> None:
    if result.get("schema_version") != RESULT_SCHEMA:
        raise ValueError("deterministic-compensator result schema changed")
    if result.get("decision_counts") != {"pass": 0, "reject": 0, "blocked": 2}:
        raise ValueError("deterministic-compensator candidate partition changed")
    if result.get("gate_counts") != {
        "candidate_actions": 2,
        "evidence_obligations": 10,
        "evidence_closed_by_compiler_hypotheses": 2,
        "evidence_absent": 8,
        "positive_candidate_mean_measures": 2,
        "compiler_compensator_theorem_interfaces": 2,
        "registered_causal_filtrations": 0,
        "action_or_QED_compensator_identities": 0,
        "exact_same_action_alternative_law_witnesses": 2,
        "paper_or_QED_Poisson_derivation_pass": 0,
        "candidate_action_reject": 0,
        "theory_ontology_observational_pass": 0,
    }:
        raise ValueError("deterministic-compensator gate counts changed")
    theorem = result.get("deterministic_compensator_Poisson_characterization", {})
    if theorem.get(
        "candidate_action_or_paper_supplies_compensator_identity"
    ) is not False or not any(
        item.startswith("conditional Poisson counts") for item in theorem.get("consequences", [])
    ):
        raise ValueError("deterministic-compensator theorem boundary changed")
    records = result.get("candidate_records", [])
    if len(records) != 2 or any(
        record.get("action_registered_event_variables") for record in records
    ):
        raise ValueError("deterministic-compensator action-variable overclaim")
    if any(record.get("action_or_QED_compensator_identity_derived") for record in records):
        raise ValueError("deterministic-compensator derivation overclaim")
    if any(record.get("candidate_action_rejection_authorized") for record in records):
        raise ValueError("deterministic-compensator gate overreached to action rejection")
    if result.get("first_blocker") != FIRST_BLOCKER:
        raise ValueError("deterministic-compensator first blocker changed")
    if any(result.get("claim_seals", {}).values()) or any(result.get("data_seals", {}).values()):
        raise ValueError("deterministic-compensator seal opened")
    if (
        result.get("content_sha256") is not None
        and _content_sha(result) != result["content_sha256"]
    ):
        raise ValueError("deterministic-compensator content hash mismatch")


def build_gate(config_path: str | Path) -> dict[str, Any]:
    config_path = Path(config_path).resolve()
    root = config_path.parents[1]
    config = json.loads(config_path.read_text(encoding="utf-8"))
    _validate_config(config)
    predecessors = {
        label: _bound_artifact(root, binding) for label, binding in config["predecessors"].items()
    }
    records = _validate_predecessors(predecessors)
    source_path = Path(__file__).resolve()
    test_path = root / "tests/test_kastner_schlatter_deterministic_compensator_admission_gate.py"
    result: dict[str, Any] = {
        "schema_version": RESULT_SCHEMA,
        "campaign_id": config["campaign_id"],
        "scope": (
            "candidate-bound deterministic-compensator characterization on regular finite-field "
            "patches; no paper, QED, action, ontology, or observational derivation inferred"
        ),
        "source_bindings": {
            **config["predecessors"],
            "primary_pdf_sha256": PDF_SHA256,
            "config": {
                "path": config_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(config_path),
            },
            "source": {
                "path": source_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(source_path),
            },
            "test": {
                "path": test_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(test_path),
            },
        },
        "theorem_domain": config["theorem_domain"],
        "deterministic_compensator_Poisson_characterization": _compensator_theorem(),
        "evidence_gap_ledger": _evidence_gap_ledger(),
        "exact_controls": _exact_controls(),
        "candidate_records": [_candidate_record(record) for record in records],
        "gate_counts": {
            "candidate_actions": 2,
            "evidence_obligations": 10,
            "evidence_closed_by_compiler_hypotheses": 2,
            "evidence_absent": 8,
            "positive_candidate_mean_measures": 2,
            "compiler_compensator_theorem_interfaces": 2,
            "registered_causal_filtrations": 0,
            "action_or_QED_compensator_identities": 0,
            "exact_same_action_alternative_law_witnesses": 2,
            "paper_or_QED_Poisson_derivation_pass": 0,
            "candidate_action_reject": 0,
            "theory_ontology_observational_pass": 0,
        },
        "decision_counts": {"pass": 0, "reject": 0, "blocked": 2},
        "decision": "conditional_compensator_characterization_closed_physical_identity_blocked",
        "first_blocker": FIRST_BLOCKER,
        "secondary_blockers": [
            SECOND_BLOCKER,
            "no_registered_nonexplosion_or_projectively_consistent_set_indexed_actualization_process",
            "no_operational_event_to_actualization_filtration_bridge",
        ],
        "claim_seals": {
            "paper_QED_compensator_identity_registered": False,
            "candidate_action_stochastic_law_derived": False,
            "candidate_action_rejected": False,
            "detector_event_equals_transaction_proven": False,
            "transaction_ontology_validated": False,
            "observational_pass": False,
            "scientific_test_pass": False,
            "theory_validity_claimed": False,
            "dark_sector_elimination_proven": False,
        },
        "data_seals": dict(config["seals"]),
    }
    result["content_sha256"] = _content_sha(result)
    _validate_result(result)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("config")
    parser.add_argument("--output")
    args = parser.parse_args()
    config_path = Path(args.config).resolve()
    result = build_gate(config_path)
    config = json.loads(config_path.read_text(encoding="utf-8"))
    output = (
        Path(args.output).resolve()
        if args.output
        else config_path.parents[1] / str(config["output_path"])
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
