"""Canonical conditional probability-space gate for transaction counts."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Mapping
from fractions import Fraction
from pathlib import Path
from typing import Any

CONFIG_SCHEMA = "sigma-kastner-schlatter-canonical-probability-space-config-1.0"
RESULT_SCHEMA = "sigma-kastner-schlatter-canonical-probability-space-gate-1.0"
FIRST_BLOCKER = (
    "no_registered_paper_QED_or_candidate_action_selection_rule_for_the_compiler_"
    "authored_Poisson_probability_space_over_same_mean_Cox_completion"
)
PDF_SHA256 = "c2f671293d07b21397e745da00a3ce1a2193c00da647a2ebf4147612b76c1780"


def _canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _sha(value: Any) -> str:
    return hashlib.sha256(_canonical(value).encode()).hexdigest()


def _file_sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _content_sha(value: Mapping[str, Any]) -> str:
    return _sha({key: item for key, item in value.items() if key != "content_sha256"})


def _inside(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise ValueError("canonical-probability path escapes repository") from error
    return path


def _bound_artifact(root: Path, binding: Mapping[str, Any]) -> dict[str, Any]:
    if set(binding) != {"path", "file_sha256", "content_sha256"}:
        raise ValueError("canonical-probability predecessor binding shape changed")
    path = _inside(root, str(binding["path"]))
    if not path.is_file() or _file_sha(path) != binding["file_sha256"]:
        raise ValueError("canonical-probability predecessor file hash mismatch")
    value = json.loads(path.read_text(encoding="utf-8"))
    if (
        not isinstance(value, dict)
        or value.get("content_sha256") != binding["content_sha256"]
        or _content_sha(value) != binding["content_sha256"]
    ):
        raise ValueError("canonical-probability predecessor content hash mismatch")
    return value


def _validate_config(config: Mapping[str, Any]) -> None:
    if (
        set(config)
        != {
            "schema_version",
            "campaign_id",
            "output_path",
            "predecessors",
            "construction_domain",
            "admission_policy",
            "seals",
        }
        or config.get("schema_version") != CONFIG_SCHEMA
    ):
        raise ValueError("canonical-probability config shape changed")
    if set(config.get("predecessors", {})) != {
        "deterministic_compensator",
        "conditional_poisson_kernel",
        "actualization_history_map",
        "qed_actualization_audit",
        "positive_reparameterization",
        "candidate_action_completion",
    }:
        raise ValueError("canonical-probability predecessor set changed")
    if config.get("construction_domain") != {
        "spacetime": "regular globally hyperbolic patch W with declared Cauchy time tau",
        "conditioning": "fixed smooth metric g and finite-real phi on relatively compact W",
        "intensity": "mu_g_phi(dx)=q0*exp(phi(x))*dVol_g(x), q0>0 and mu_g_phi(W)<infinity",
        "configuration_space": (
            "N_lf(W), the locally finite integer-valued Borel measures on W"
        ),
        "sigma_algebra": (
            "evaluation sigma-algebra generated by eta -> eta(B) for relatively compact Borel B"
        ),
        "filtration": (
            "P_mu-completed right-continuous natural filtration generated by counts in "
            "W_t={x in W:tau(x)<=t}"
        ),
    }:
        raise ValueError("canonical-probability construction domain changed")
    if config.get("admission_policy") != {
        "compiler_may_construct_conditional_probability_space": True,
        "compiler_construction_counts_as_paper_or_QED_derivation": False,
        "deterministic_action_selects_stochastic_completion": False,
        "same_mean_measure_selects_Poisson": False,
        "candidate_action_rejection_allowed": False,
    }:
        raise ValueError("canonical-probability admission policy changed")
    if any(config.get("seals", {}).values()):
        raise ValueError("canonical-probability seal opened")


def _validate_predecessors(values: Mapping[str, Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    compensator = values["deterministic_compensator"]
    if (
        compensator.get("content_sha256")
        != "40ee8fc7d6c1f2492edc19edaa7c9dd794b62d37464b26f0d72058ff4eecdaba"
        or compensator.get("decision_counts") != {"blocked": 2, "pass": 0, "reject": 0}
        or compensator.get("first_blocker")
        != "no_registered_QED_probability_space_causal_filtration_or_deterministic_compensator_martingale_identity"
        or compensator.get("gate_counts", {}).get("registered_causal_filtrations") != 0
        or compensator.get("gate_counts", {}).get("action_or_QED_compensator_identities") != 0
        or any(compensator.get("claim_seals", {}).values())
        or any(compensator.get("data_seals", {}).values())
    ):
        raise ValueError("deterministic-compensator boundary changed")

    conditional = values["conditional_poisson_kernel"]
    if (
        conditional.get("decision_counts") != {"blocked": 2, "pass": 0, "reject": 0}
        or conditional.get("gate_counts", {}).get("compiler_authored_conditional_kernels") != 2
        or conditional.get("gate_counts", {}).get("conditional_Laplace_selector_pass") != 2
        or conditional.get("gate_counts", {}).get("paper_or_QED_actualization_derivation_pass")
        != 0
    ):
        raise ValueError("conditional-Poisson boundary changed")

    history = values["actualization_history_map"]
    if (
        history.get("decision_counts") != {"blocked": 2, "pass": 0, "reject": 0}
        or history.get("gate_counts", {}).get("paper_complete_history_to_counting_measure_maps")
        != 0
        or history.get("compiler_conditional_count_map", {}).get("selects_a_probability_law")
        is not False
    ):
        raise ValueError("actualization-history boundary changed")

    qed = values["qed_actualization_audit"]
    if (
        qed.get("decision_counts") != {"blocked": 2, "pass": 0, "reject": 0}
        or qed.get("gate_counts", {}).get("paper_or_QED_channel_kernels_registered") != 0
        or any(qed.get("claim_seals", {}).values())
        or any(qed.get("data_seals", {}).values())
    ):
        raise ValueError("QED-actualization boundary changed")

    positive = values["positive_reparameterization"]
    records = positive.get("candidate_records", [])
    if (
        [record.get("branch_id") for record in records]
        != ["eq35_middle_h", "eq35_printed_planck"]
        or any(
            record.get("field_diffeomorphism", {}).get("map") != "q=q0*exp(phi)"
            for record in records
        )
        or positive.get("gate_counts", {}).get("action_derived_point_process_measure_pass")
        != 0
    ):
        raise ValueError("positive-reparameterization boundary changed")

    action = values["candidate_action_completion"]
    hypotheses = action.get("completion_hypotheses", [])
    if (
        [record.get("branch_id") for record in hypotheses]
        != ["eq35_middle_h", "eq35_printed_planck"]
        or any(
            record.get("candidate_action", {}).get("stochastic_law_derived_by_action")
            for record in hypotheses
        )
        or any(record.get("paper_authorship_or_derivation") for record in hypotheses)
    ):
        raise ValueError("candidate-action stochastic boundary changed")
    return records


def _canonical_construction() -> dict[str, Any]:
    return {
        "attribution": (
            "compiler_authored_conditional_construction_not_in_or_derived_by_the_paper_or_QED"
        ),
        "probability_space": {
            "sample_space": "Omega=N_lf(W)",
            "sample_point": "eta, a locally finite integer-valued Borel measure",
            "sigma_algebra": "F=sigma{eta->eta(B): B relatively compact Borel}",
            "probability_measure": (
                "P_mu is the unique PRM(mu_g_phi) law fixed by its Laplace functional"
            ),
            "coordinate_counting_measure": "N(eta,B)=eta(B)",
            "finite_volume_nonexplosion": "N(W)<infinity P_mu-almost surely because mu(W)<infinity",
        },
        "causal_filtration": {
            "past_region": "W_t={x in W:tau(x)<=t}",
            "raw": "F_t^0=sigma{N(B): B subset W_t relatively compact Borel}",
            "usual_augmentation": "F_t=intersection_{u>t}(F_u^0 joined with P_mu-null sets)",
            "right_continuous": True,
            "complete": True,
            "coordinate_measure_adapted": True,
        },
        "compensator_martingale": {
            "deterministic_compensator": "A(B)=mu_g_phi(B)",
            "simple_predictable_integrand": (
                "h=sum_j H_j*1_(t_(j-1),t_j]xB_j with bounded F_t_(j-1)-measurable H_j"
            ),
            "martingale": "M_t(h)=Integral_{W_t} h*(dN-dmu)",
            "proof_interface": (
                "PRM independent increments make every new-slab centered increment have "
                "conditional expectation zero; bounded simple h follows by linearity and "
                "the predictable L1 closure follows by localization"
            ),
            "exponential_martingale": (
                "Z_t(f)=exp(-Integral_{W_t}f*dN+Integral_{W_t}(1-exp(-f))*dmu)"
            ),
            "conditional_Laplace_conclusion": (
                "E[exp(-Integral_{W_t\\W_s}f*dN)|F_s,g,phi]="
                "exp(-Integral_{W_t\\W_s}(1-exp(-f))*dmu)"
            ),
        },
        "projective_extension": {
            "finite_partitions": (
                "for disjoint B_i, (N(B_i))_i has product Poisson laws with means mu(B_i)"
            ),
            "consistency": "partition coarsening maps sums of component counts",
            "uniqueness": "the evaluation sigma-algebra is fixed by all finite-partition laws",
            "global_claim": (
                "only locally finite regular patches; no singular or infinite-intensity extension"
            ),
        },
        "paper_or_QED_supplies_this_probability_space": False,
        "candidate_action_selects_this_probability_space": False,
    }


def _exact_controls() -> dict[str, Any]:
    means = [Fraction(2), Fraction(3)]
    pgf_points = [Fraction(1, 2), Fraction(1, 3)]
    joint_exponent = sum(
        (mean * (point - 1) for mean, point in zip(means, pgf_points, strict=True)),
        Fraction(0),
    )
    slab_mean = Fraction(3, 2)
    mixing_values = [Fraction(1, 2), Fraction(3, 2)]
    mixing_mean = sum(mixing_values, Fraction(0)) / len(mixing_values)
    mixing_second = sum((value * value for value in mixing_values), Fraction(0)) / len(
        mixing_values
    )
    witness_mean = Fraction(2)
    return {
        "finite_partition_PGF_positive_control": {
            "cell_means": ["2", "3"],
            "PGF_points": ["1/2", "1/3"],
            "joint_exponent": str(joint_exponent),
            "factorized_exponent": "-3",
            "pass": joint_exponent == -3,
        },
        "centered_increment_martingale_positive_control": {
            "new_slab_mean": str(slab_mean),
            "conditional_expected_count_increment": str(slab_mean),
            "conditional_centered_increment": "0",
            "pass": slab_mean - slab_mean == 0,
        },
        "exponential_martingale_positive_control": {
            "new_slab_mean": str(slab_mean),
            "test_value_exp_minus_f": "1/2",
            "Poisson_Laplace_factor": "exp(-3/4)",
            "compensating_factor": "exp(3/4)",
            "conditional_product": "1",
            "pass": True,
        },
        "same_action_Cox_nonidentifiability": {
            "mixing_variable": "Z in {1/2,3/2} equiprobable and F_0-measurable",
            "E_Z": str(mixing_mean),
            "E_Z_squared": str(mixing_second),
            "completion_A": "P_mu=PRM(mu_g_phi)",
            "completion_B": "P_Cox=Integral PRM(z*mu_g_phi)dnu(z)",
            "same_conditional_mean_given_g_phi": mixing_mean == 1,
            "same_deterministic_candidate_action": True,
            "Poisson_variance_at_mu_2": "2",
            "Cox_variance_at_mu_2": str(
                witness_mean + witness_mean * witness_mean * (mixing_second - mixing_mean**2)
            ),
            "Poisson_second_factorial_moment_at_mu_2": "4",
            "Cox_second_factorial_moment_at_mu_2": str(witness_mean**2 * mixing_second),
            "Cox_predictable_compensator_in_enlarged_filtration": "Z*mu_g_phi",
            "deterministic_mu_compensator_identity_holds_for_Cox": False,
            "action_selects_between_completions": False,
        },
        "history_pushforward_negative_control": {
            "compiler_count_map": "N_h(B)=sum_tau 1_B(a_h(tau))",
            "missing_inputs": [
                "measurable actualization-history sample space",
                "probability law on histories",
                "measurable pushforward into N_lf(W)",
            ],
            "identify_canonical_eta_with_a_paper_history_law": False,
        },
        "action_variable_negative_control": {
            "registered_action_variables": ["g_mn", "phi"],
            "absent_stochastic_variables": ["eta", "Omega", "F", "F_t", "P_mu", "N"],
            "variational_derivation_of_P_mu_or_compensator": False,
        },
    }


def _evidence_ledger() -> list[dict[str, str]]:
    return [
        {"obligation": "locally_finite_configuration_space", "status": "closed_by_compiler"},
        {"obligation": "evaluation_sigma_algebra", "status": "closed_by_compiler"},
        {"obligation": "conditional_Poisson_probability_measure", "status": "closed_by_compiler"},
        {"obligation": "completed_right_continuous_causal_filtration", "status": "closed_by_compiler"},
        {"obligation": "adapted_coordinate_counting_measure", "status": "closed_by_compiler"},
        {"obligation": "deterministic_compensator_martingale_identity", "status": "closed_by_compiler"},
        {"obligation": "paper_or_QED_probability_space_and_filtration", "status": "absent"},
        {"obligation": "action_or_QED_selection_of_P_mu", "status": "absent"},
        {"obligation": "measurable_actualization_history_pushforward_law", "status": "absent"},
        {"obligation": "operational_event_filtration", "status": "absent"},
    ]


def _candidate_record(record: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "branch_id": record["branch_id"],
        "beta": record["beta"],
        "candidate_intensity": "mu_g_phi(dx)=q0*exp(phi(x))*dVol_g(x)",
        "compiler_canonical_probability_space": "pass",
        "compiler_causal_filtration": "pass",
        "compiler_compensator_martingale_identity": "pass",
        "paper_or_QED_probability_space_derived": False,
        "candidate_action_selects_Poisson_completion": False,
        "same_action_Cox_completion_witness": True,
        "candidate_action_rejection_authorized": False,
        "candidate_decision": "blocked",
        "first_blocker": FIRST_BLOCKER,
    }


EXPECTED_COUNTS = {
    "candidate_actions": 2,
    "evidence_obligations": 10,
    "evidence_closed_by_compiler_construction": 6,
    "evidence_absent": 4,
    "compiler_canonical_configuration_spaces": 2,
    "compiler_conditional_probability_measures": 2,
    "compiler_completed_causal_filtrations": 2,
    "compiler_compensator_martingale_identities": 2,
    "paper_or_QED_probability_spaces": 0,
    "action_or_QED_stochastic_selection_rules": 0,
    "exact_same_action_Cox_witnesses": 2,
    "candidate_action_reject": 0,
    "theory_ontology_observational_pass": 0,
}


def _validate_result(result: Mapping[str, Any]) -> None:
    if result.get("schema_version") != RESULT_SCHEMA:
        raise ValueError("canonical-probability result schema changed")
    if result.get("decision_counts") != {"pass": 0, "reject": 0, "blocked": 2}:
        raise ValueError("canonical-probability candidate partition changed")
    if result.get("gate_counts") != EXPECTED_COUNTS:
        raise ValueError("canonical-probability gate counts changed")
    construction = result.get("canonical_conditional_construction", {})
    if (
        construction.get("paper_or_QED_supplies_this_probability_space") is not False
        or construction.get("candidate_action_selects_this_probability_space") is not False
        or construction.get("causal_filtration", {}).get("right_continuous") is not True
        or construction.get("causal_filtration", {}).get("complete") is not True
    ):
        raise ValueError("canonical-probability attribution or filtration overclaim")
    controls = result.get("exact_controls", {})
    if (
        controls.get("finite_partition_PGF_positive_control", {}).get("joint_exponent") != "-3"
        or controls.get("centered_increment_martingale_positive_control", {}).get(
            "conditional_centered_increment"
        )
        != "0"
        or controls.get("same_action_Cox_nonidentifiability", {}).get(
            "Cox_variance_at_mu_2"
        )
        != "3"
        or controls.get("same_action_Cox_nonidentifiability", {}).get(
            "Cox_second_factorial_moment_at_mu_2"
        )
        != "5"
    ):
        raise ValueError("canonical-probability exact control changed")
    records = result.get("candidate_records", [])
    if len(records) != 2 or any(
        record.get("candidate_decision") != "blocked"
        or record.get("compiler_canonical_probability_space") != "pass"
        or record.get("compiler_compensator_martingale_identity") != "pass"
        or record.get("paper_or_QED_probability_space_derived") is not False
        or record.get("candidate_action_selects_Poisson_completion") is not False
        or record.get("candidate_action_rejection_authorized") is not False
        for record in records
    ):
        raise ValueError("canonical-probability candidate boundary changed")
    if result.get("first_blocker") != FIRST_BLOCKER:
        raise ValueError("canonical-probability first blocker changed")
    if any(result.get("claim_seals", {}).values()) or any(result.get("data_seals", {}).values()):
        raise ValueError("canonical-probability seal opened")
    if (
        result.get("content_sha256") is not None
        and _content_sha(result) != result["content_sha256"]
    ):
        raise ValueError("canonical-probability content hash mismatch")


def build_gate(config_path: str | Path) -> dict[str, Any]:
    config_path = Path(config_path).resolve()
    root = config_path.parents[1]
    config = json.loads(config_path.read_text(encoding="utf-8"))
    _validate_config(config)
    predecessors = {
        label: _bound_artifact(root, binding) for label, binding in config["predecessors"].items()
    }
    records = _validate_predecessors(predecessors)
    source_path = Path(__file__).resolve()
    test_path = root / "tests/test_kastner_schlatter_canonical_probability_space_gate.py"
    result: dict[str, Any] = {
        "schema_version": RESULT_SCHEMA,
        "campaign_id": config["campaign_id"],
        "scope": (
            "candidate-bound compiler construction of a canonical conditional Poisson "
            "probability space, causal filtration, and compensator martingale; no physical "
            "selection, paper/QED derivation, action rejection, ontology, or observation inferred"
        ),
        "source_bindings": {
            **config["predecessors"],
            "primary_pdf_sha256": PDF_SHA256,
            "config": {
                "path": config_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(config_path),
            },
            "source": {
                "path": source_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(source_path),
            },
            "test": {
                "path": test_path.relative_to(root).as_posix(),
                "file_sha256": _file_sha(test_path),
            },
        },
        "construction_domain": config["construction_domain"],
        "canonical_conditional_construction": _canonical_construction(),
        "evidence_gap_ledger": _evidence_ledger(),
        "exact_controls": _exact_controls(),
        "candidate_records": [_candidate_record(record) for record in records],
        "gate_counts": dict(EXPECTED_COUNTS),
        "decision_counts": {"pass": 0, "reject": 0, "blocked": 2},
        "decision": "canonical_conditional_probability_space_closed_physical_selection_blocked",
        "first_blocker": FIRST_BLOCKER,
        "secondary_blockers": [
            "no_registered_measurable_QED_actualization_history_law_with_Poisson_pushforward",
            "no_candidate_action_variables_or_variation_for_event_random_measures",
            "no_operational_transaction_event_filtration_or_exposure_bundle",
            "no_global_singular_or_infinite_intensity_probability_space_extension",
        ],
        "claim_seals": {
            "paper_QED_probability_space_registered": False,
            "paper_QED_compensator_identity_registered": False,
            "candidate_action_stochastic_law_derived": False,
            "candidate_action_rejected": False,
            "detector_event_equals_transaction_proven": False,
            "transaction_ontology_validated": False,
            "observational_pass": False,
            "scientific_test_pass": False,
            "theory_validity_claimed": False,
            "dark_sector_elimination_proven": False,
        },
        "data_seals": dict(config["seals"]),
    }
    result["content_sha256"] = _content_sha(result)
    _validate_result(result)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("config")
    parser.add_argument("--output")
    args = parser.parse_args()
    config_path = Path(args.config).resolve()
    result = build_gate(config_path)
    config = json.loads(config_path.read_text(encoding="utf-8"))
    output = (
        Path(args.output).resolve()
        if args.output
        else config_path.parents[1] / str(config["output_path"])
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
