"""Rotation-equivariant, one-potential features for spent cluster inference.

This module is deliberately an inverse-problem diagnostic rather than a gravity
law.  Every feature is converted into a convergence/shear triplet belonging to
one scalar lens potential.  A fitted coefficient therefore cannot rotate or
rescale the two shear components independently.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.ndimage import gaussian_filter

FAMILY_ORDER = {
    "scalar_scale": 0,
    "total_tidal": 1,
    "component_overlap": 2,
}


@dataclass(frozen=True)
class MetricFeature:
    """A dimensionless Hessian triplet generated by one lens potential."""

    name: str
    family: str
    convergence: np.ndarray
    shear_1: np.ndarray
    shear_2: np.ndarray

    def __post_init__(self) -> None:
        arrays = tuple(
            np.asarray(value, dtype=float)
            for value in (self.convergence, self.shear_1, self.shear_2)
        )
        if self.family not in FAMILY_ORDER:
            raise ValueError(f"unknown feature family {self.family}")
        if not self.name or arrays[0].ndim != 2:
            raise ValueError("feature names must be nonempty and maps two-dimensional")
        if any(value.shape != arrays[0].shape for value in arrays[1:]):
            raise ValueError("all feature channels must have the same shape")
        if any(np.any(~np.isfinite(value)) for value in arrays):
            raise ValueError("feature maps must be finite")


@dataclass(frozen=True)
class EquivariantDataset:
    """One spent cluster regression dataset on a common pixel mask."""

    name: str
    mask: np.ndarray
    base: tuple[np.ndarray, np.ndarray, np.ndarray]
    target: tuple[np.ndarray, np.ndarray, np.ndarray]
    features: dict[str, MetricFeature]

    def __post_init__(self) -> None:
        mask = np.asarray(self.mask, dtype=bool)
        if mask.ndim != 2 or not np.any(mask):
            raise ValueError("dataset mask must be a nonempty two-dimensional array")
        for channels in (self.base, self.target):
            if len(channels) != 3:
                raise ValueError("base and target must contain convergence and two shears")
            for channel in channels:
                values = np.asarray(channel, dtype=float)
                if values.shape != mask.shape or np.any(~np.isfinite(values[mask])):
                    raise ValueError("dataset channels must match the finite masked grid")
        if not self.features:
            raise ValueError("dataset must contain features")
        if any(feature.convergence.shape != mask.shape for feature in self.features.values()):
            raise ValueError("feature grids must match the dataset mask")


@dataclass(frozen=True)
class RidgeFit:
    """Raw feature coefficients from the equivariant ridge solve."""

    coefficients: dict[str, float]
    alpha: float
    standardized_condition_number: float


def _padded_fft(field: np.ndarray, padding_factor: int) -> tuple[np.ndarray, tuple[slice, slice]]:
    values = np.asarray(field, dtype=float)
    if values.ndim != 2 or min(values.shape) < 5 or np.any(~np.isfinite(values)):
        raise ValueError("field must be a finite two-dimensional array")
    if padding_factor < 1:
        raise ValueError("padding_factor must be at least one")
    target_shape = tuple(padding_factor * size for size in values.shape)
    before = tuple((target - size) // 2 for target, size in zip(target_shape, values.shape))
    after = tuple(
        target - size - start for target, size, start in zip(target_shape, values.shape, before)
    )
    padded = np.pad(values, tuple(zip(before, after, strict=True)), mode="constant")
    crop = tuple(slice(start, start + size) for start, size in zip(before, values.shape))
    return np.fft.fft2(padded), crop


def _spin_two_kernels(shape: tuple[int, int]) -> tuple[np.ndarray, np.ndarray]:
    k_north = 2.0 * np.pi * np.fft.fftfreq(shape[0])
    k_east = 2.0 * np.pi * np.fft.fftfreq(shape[1])
    east, north = np.meshgrid(k_east, k_north)
    squared = np.square(east) + np.square(north)
    kernel_1 = np.zeros(shape, dtype=float)
    kernel_2 = np.zeros(shape, dtype=float)
    nonzero = squared > 0.0
    kernel_1[nonzero] = (np.square(east[nonzero]) - np.square(north[nonzero])) / squared[nonzero]
    kernel_2[nonzero] = 2.0 * east[nonzero] * north[nonzero] / squared[nonzero]
    return kernel_1, kernel_2


def convergence_to_shear(
    convergence: np.ndarray,
    *,
    padding_factor: int = 2,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the pure E-mode shear belonging to a convergence map."""
    transformed, crop = _padded_fft(convergence, padding_factor)
    kernel_1, kernel_2 = _spin_two_kernels(transformed.shape)
    shear_1 = np.fft.ifft2(kernel_1 * transformed).real[crop]
    shear_2 = np.fft.ifft2(kernel_2 * transformed).real[crop]
    return shear_1, shear_2


def tensor_e_projection(
    tensor_1: np.ndarray,
    tensor_2: np.ndarray,
    *,
    padding_factor: int = 2,
) -> np.ndarray:
    """Contract a spin-two tensor with the E projector to obtain a scalar source."""
    first, crop = _padded_fft(tensor_1, padding_factor)
    second, other_crop = _padded_fft(tensor_2, padding_factor)
    if first.shape != second.shape or crop != other_crop:
        raise ValueError("tensor components must have matching shapes")
    kernel_1, kernel_2 = _spin_two_kernels(first.shape)
    projected = np.fft.ifft2(kernel_1 * first + kernel_2 * second).real
    return projected[crop]


def _metric_feature(
    name: str,
    family: str,
    convergence: np.ndarray,
    *,
    padding_factor: int,
) -> MetricFeature:
    shear_1, shear_2 = convergence_to_shear(
        convergence,
        padding_factor=padding_factor,
    )
    return MetricFeature(
        name=name,
        family=family,
        convergence=np.asarray(convergence, dtype=float),
        shear_1=shear_1,
        shear_2=shear_2,
    )


def _tensor_metric_feature(
    name: str,
    family: str,
    tensor_1: np.ndarray,
    tensor_2: np.ndarray,
    *,
    padding_factor: int,
) -> MetricFeature:
    convergence = tensor_e_projection(
        tensor_1,
        tensor_2,
        padding_factor=padding_factor,
    )
    return _metric_feature(
        name,
        family,
        convergence,
        padding_factor=padding_factor,
    )


def _derivatives(field: np.ndarray, spacing: float) -> dict[str, np.ndarray]:
    north, east = np.gradient(field, spacing, spacing, edge_order=2)
    north_north, north_east = np.gradient(north, spacing, spacing, edge_order=2)
    east_north, east_east = np.gradient(east, spacing, spacing, edge_order=2)
    cross = 0.5 * (north_east + east_north)
    return {
        "north": north,
        "east": east,
        "north_north": north_north,
        "east_east": east_east,
        "cross": cross,
    }


def build_metric_feature_library(
    total_convergence: np.ndarray,
    gas_convergence: np.ndarray,
    stellar_convergence: np.ndarray,
    *,
    spacing_kpc: float,
    scales_kpc: tuple[float, ...],
    padding_factor: int = 2,
    component_floor: float = 1.0e-12,
) -> list[MetricFeature]:
    """Build the frozen nested scalar, tidal, and component feature library."""
    total = np.asarray(total_convergence, dtype=float)
    gas = np.asarray(gas_convergence, dtype=float)
    stars = np.asarray(stellar_convergence, dtype=float)
    if total.ndim != 2 or total.shape != gas.shape or total.shape != stars.shape:
        raise ValueError("baryonic convergence maps must have matching two-dimensional shapes")
    if any(np.any(~np.isfinite(values)) for values in (total, gas, stars)):
        raise ValueError("baryonic convergence maps must be finite")
    if np.any(total < 0.0) or np.any(gas < 0.0) or np.any(stars < 0.0):
        raise ValueError("baryonic convergence maps must be nonnegative")
    if spacing_kpc <= 0.0 or component_floor <= 0.0 or not scales_kpc:
        raise ValueError("spacing, component floor, and scales must be positive")

    features: list[MetricFeature] = []
    for scale in scales_kpc:
        if scale <= 0.0:
            raise ValueError("all Gaussian scales must be positive")
        sigma_pixels = scale / spacing_kpc
        smoothed_total = gaussian_filter(total, sigma_pixels, mode="constant")
        smoothed_gas = gaussian_filter(gas, sigma_pixels, mode="constant")
        smoothed_stars = gaussian_filter(stars, sigma_pixels, mode="constant")
        tag = f"{scale:g}kpc"

        features.append(
            _metric_feature(
                f"total_smooth_{tag}",
                "scalar_scale",
                smoothed_total,
                padding_factor=padding_factor,
            )
        )

        total_d = _derivatives(smoothed_total, spacing_kpc)
        gradient_magnitude = scale * np.hypot(total_d["east"], total_d["north"])
        features.append(
            _metric_feature(
                f"total_gradient_magnitude_{tag}",
                "total_tidal",
                gradient_magnitude,
                padding_factor=padding_factor,
            )
        )
        hessian_1 = 0.5 * scale**2 * (total_d["east_east"] - total_d["north_north"])
        hessian_2 = scale**2 * total_d["cross"]
        features.append(
            _tensor_metric_feature(
                f"total_hessian_axis_{tag}",
                "total_tidal",
                hessian_1,
                hessian_2,
                padding_factor=padding_factor,
            )
        )
        gradient_axis_1 = (
            0.5 * scale**2 * (np.square(total_d["east"]) - np.square(total_d["north"]))
        )
        gradient_axis_2 = scale**2 * total_d["east"] * total_d["north"]
        features.append(
            _tensor_metric_feature(
                f"total_gradient_axis_{tag}",
                "total_tidal",
                gradient_axis_1,
                gradient_axis_2,
                padding_factor=padding_factor,
            )
        )

        denominator = smoothed_gas + smoothed_stars + component_floor
        mixing = 4.0 * smoothed_gas * smoothed_stars / denominator
        contrast = smoothed_gas - smoothed_stars
        features.append(
            _metric_feature(
                f"gas_star_mixing_{tag}",
                "component_overlap",
                mixing,
                padding_factor=padding_factor,
            )
        )
        features.append(
            _metric_feature(
                f"gas_minus_star_{tag}",
                "component_overlap",
                contrast,
                padding_factor=padding_factor,
            )
        )

        gas_d = _derivatives(smoothed_gas, spacing_kpc)
        star_d = _derivatives(smoothed_stars, spacing_kpc)
        cross_1 = (
            0.5 * scale**2 * (gas_d["east"] * star_d["east"] - gas_d["north"] * star_d["north"])
        )
        cross_2 = (
            0.5 * scale**2 * (gas_d["east"] * star_d["north"] + gas_d["north"] * star_d["east"])
        )
        features.append(
            _tensor_metric_feature(
                f"gas_star_cross_gradient_{tag}",
                "component_overlap",
                cross_1,
                cross_2,
                padding_factor=padding_factor,
            )
        )
        difference_east = gas_d["east"] - star_d["east"]
        difference_north = gas_d["north"] - star_d["north"]
        difference_1 = 0.5 * scale**2 * (np.square(difference_east) - np.square(difference_north))
        difference_2 = scale**2 * difference_east * difference_north
        features.append(
            _tensor_metric_feature(
                f"gas_star_difference_gradient_{tag}",
                "component_overlap",
                difference_1,
                difference_2,
                padding_factor=padding_factor,
            )
        )

    if len({feature.name for feature in features}) != len(features):
        raise RuntimeError("feature names must be unique")
    return features


def features_for_family(
    features: dict[str, MetricFeature] | list[MetricFeature],
    family: str,
) -> list[MetricFeature]:
    """Return the declared nested family in deterministic name order."""
    if family not in FAMILY_ORDER:
        raise ValueError(f"unknown feature family {family}")
    values = list(features.values()) if isinstance(features, dict) else list(features)
    return sorted(
        (value for value in values if FAMILY_ORDER[value.family] <= FAMILY_ORDER[family]),
        key=lambda value: value.name,
    )


def _triplet_vector(
    channels: tuple[np.ndarray, np.ndarray, np.ndarray], mask: np.ndarray
) -> np.ndarray:
    return np.concatenate([np.asarray(channel, dtype=float)[mask] for channel in channels])


def _feature_vector(feature: MetricFeature, mask: np.ndarray) -> np.ndarray:
    return _triplet_vector(
        (feature.convergence, feature.shear_1, feature.shear_2),
        mask,
    )


def _residual_channels(dataset: EquivariantDataset) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    return tuple(
        np.asarray(target, dtype=float) - np.asarray(base, dtype=float)
        for target, base in zip(dataset.target, dataset.base, strict=True)
    )


def _output_weights(dataset: EquivariantDataset) -> np.ndarray:
    residual = _residual_channels(dataset)
    scalar_rms = float(np.sqrt(np.mean(np.square(residual[0][dataset.mask]))))
    spin_rms = float(
        np.sqrt(
            0.5
            * np.mean(np.square(residual[1][dataset.mask]) + np.square(residual[2][dataset.mask]))
        )
    )
    tiny = np.finfo(float).tiny
    scalar_rms = max(scalar_rms, tiny)
    spin_rms = max(spin_rms, tiny)
    size = int(np.count_nonzero(dataset.mask))
    return np.concatenate(
        [
            np.full(size, 1.0 / scalar_rms),
            np.full(size, 1.0 / spin_rms),
            np.full(size, 1.0 / spin_rms),
        ]
    )


def fit_equivariant_ridge(
    datasets: list[EquivariantDataset],
    *,
    family: str,
    alpha: float,
) -> RidgeFit:
    """Fit one coefficient vector with scalar/spin channel covariance preserved."""
    if not datasets:
        raise ValueError("datasets must be nonempty")
    names = [feature.name for feature in features_for_family(datasets[0].features, family)]
    return fit_equivariant_ridge_features(
        datasets,
        feature_names=names,
        alpha=alpha,
    )


def fit_equivariant_ridge_features(
    datasets: list[EquivariantDataset],
    *,
    feature_names: list[str] | tuple[str, ...],
    alpha: float,
) -> RidgeFit:
    """Fit an explicit shared feature list without using the v15 family hierarchy."""
    if not datasets or alpha < 0.0 or not np.isfinite(alpha):
        raise ValueError("datasets must be nonempty and alpha finite and nonnegative")
    names = list(feature_names)
    if not names:
        raise ValueError("the requested feature list is empty")
    if len(set(names)) != len(names):
        raise ValueError("feature names must be unique")
    matrices = []
    targets = []
    for dataset in datasets:
        if any(name not in dataset.features for name in names):
            raise ValueError("all datasets must expose every requested feature")
        weights = _output_weights(dataset)
        matrix = np.column_stack(
            [_feature_vector(dataset.features[name], dataset.mask) for name in names]
        )
        target = _triplet_vector(_residual_channels(dataset), dataset.mask)
        matrices.append(matrix * weights[:, None])
        targets.append(target * weights)
    design = np.vstack(matrices)
    target = np.concatenate(targets)
    column_scale = np.sqrt(np.mean(np.square(design), axis=0))
    if np.any(~np.isfinite(column_scale)) or np.any(column_scale <= 0.0):
        raise ValueError("every feature must have finite nonzero training support")
    standardized = design / column_scale
    if alpha == 0.0:
        standardized_coefficients = np.linalg.lstsq(standardized, target, rcond=None)[0]
    else:
        sample_count = float(len(target))
        gram = standardized.T @ standardized / sample_count
        rhs = standardized.T @ target / sample_count
        standardized_coefficients = np.linalg.solve(
            gram + alpha * np.eye(len(names)),
            rhs,
        )
    raw = standardized_coefficients / column_scale
    condition = float(np.linalg.cond(standardized.T @ standardized / len(target)))
    return RidgeFit(
        coefficients={name: float(value) for name, value in zip(names, raw, strict=True)},
        alpha=float(alpha),
        standardized_condition_number=condition,
    )


def predict_residual(
    dataset: EquivariantDataset,
    coefficients: dict[str, float],
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Evaluate a coefficient vector without an intercept or object-specific term."""
    predicted = [np.zeros_like(dataset.target[0], dtype=float) for _ in range(3)]
    for name, coefficient in coefficients.items():
        if name not in dataset.features or not np.isfinite(coefficient):
            raise ValueError(f"invalid coefficient feature {name}")
        feature = dataset.features[name]
        for index, channel in enumerate((feature.convergence, feature.shear_1, feature.shear_2)):
            predicted[index] += float(coefficient) * channel
    return tuple(predicted)


def score_prediction(
    dataset: EquivariantDataset,
    coefficients: dict[str, float],
) -> dict[str, float]:
    """Score the full halo field and the missing AQUAL-to-halo residual."""
    predicted_residual = predict_residual(dataset, coefficients)
    target_residual = _residual_channels(dataset)
    predicted_full = tuple(
        base + residual for base, residual in zip(dataset.base, predicted_residual, strict=True)
    )

    full_terms = []
    residual_terms = []
    for predicted, target, predicted_delta, target_delta in zip(
        predicted_full,
        dataset.target,
        predicted_residual,
        target_residual,
        strict=True,
    ):
        target_values = target[dataset.mask]
        target_delta_values = target_delta[dataset.mask]
        full_terms.append(
            float(
                np.sum(np.square(predicted[dataset.mask] - target_values))
                / np.sum(np.square(target_values))
            )
        )
        residual_terms.append(
            float(
                np.sum(np.square(predicted_delta[dataset.mask] - target_delta_values))
                / np.sum(np.square(target_delta_values))
            )
        )
    full_nrmse = float(np.sqrt(np.mean(full_terms)))
    residual_nrmse = float(np.sqrt(np.mean(residual_terms)))

    predicted_spin = np.column_stack(
        [predicted_residual[1][dataset.mask], predicted_residual[2][dataset.mask]]
    )
    target_spin = np.column_stack(
        [target_residual[1][dataset.mask], target_residual[2][dataset.mask]]
    )
    denominator = float(np.linalg.norm(predicted_spin) * np.linalg.norm(target_spin))
    shear_alignment = (
        float(np.sum(predicted_spin * target_spin) / denominator) if denominator > 0.0 else 0.0
    )
    predicted_convergence = predicted_residual[0][dataset.mask]
    target_convergence = target_residual[0][dataset.mask]
    convergence_correlation = (
        float(np.corrcoef(predicted_convergence, target_convergence)[0, 1])
        if np.std(predicted_convergence) > 0.0 and np.std(target_convergence) > 0.0
        else 0.0
    )
    return {
        "full_field_NRMSE": full_nrmse,
        "residual_NRMSE": residual_nrmse,
        "residual_power_closed": float(1.0 - residual_nrmse**2),
        "residual_shear_alignment_cosine": shear_alignment,
        "residual_convergence_correlation": convergence_correlation,
    }
