"""Three-dimensional cubic Hessian equation for the Sigma v7C construction gate.

The dimensionless static equation is the cubic Galileon/Vainshtein representative

    3 Laplacian(pi) + kappa[(Laplacian(pi))^2 - H_ij H_ij] = source.

It is the helicity-zero decoupling-limit structure generated by ghost-free
massive gravity.  The solver uses a damped Picard iteration with exact
Dirichlet Poisson substeps.  It is intended for construction and manufactured
solution tests before any observational use.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

import numpy as np

from voidscreen.field_solvers import (
    _spacing3,
    _validate_grid,
    laplacian,
    normalized_residual_rms,
    solve_poisson_dirichlet,
)

Array = np.ndarray


@dataclass(frozen=True)
class CubicHessianSolution:
    potential: Array
    residual_rms: float
    converged: bool
    iterations: int
    minimum_temporal_kinetic_coefficient: float
    minimum_ellipticity_eigenvalue: float
    residual_history: tuple[float, ...]


def hessian_components(
    potential: Array,
    spacing: float | Sequence[float],
) -> tuple[Array, Array, Array, Array, Array, Array]:
    """Return ``Hxx,Hyy,Hzz,Hxy,Hxz,Hyz`` on a Cartesian grid."""

    values = _validate_grid(potential)
    steps = _spacing3(spacing)
    result = [np.zeros_like(values) for _ in range(6)]
    interior = (slice(1, -1),) * 3
    center = values[interior]
    for axis, (slot, step) in enumerate(zip(range(3), steps, strict=True)):
        before = [slice(1, -1)] * 3
        after = [slice(1, -1)] * 3
        before[axis] = slice(0, -2)
        after[axis] = slice(2, None)
        result[slot][interior] = (
            values[tuple(before)] - 2.0 * center + values[tuple(after)]
        ) / step**2

    cross_specs = ((0, 1, 3), (0, 2, 4), (1, 2, 5))
    for first, second, slot in cross_specs:
        plus_plus = [slice(1, -1)] * 3
        plus_minus = [slice(1, -1)] * 3
        minus_plus = [slice(1, -1)] * 3
        minus_minus = [slice(1, -1)] * 3
        plus_plus[first] = slice(2, None)
        plus_plus[second] = slice(2, None)
        plus_minus[first] = slice(2, None)
        plus_minus[second] = slice(0, -2)
        minus_plus[first] = slice(0, -2)
        minus_plus[second] = slice(2, None)
        minus_minus[first] = slice(0, -2)
        minus_minus[second] = slice(0, -2)
        result[slot][interior] = (
            values[tuple(plus_plus)]
            - values[tuple(plus_minus)]
            - values[tuple(minus_plus)]
            + values[tuple(minus_minus)]
        ) / (4.0 * steps[first] * steps[second])
    return tuple(result)


def cubic_hessian_invariant(
    potential: Array,
    spacing: float | Sequence[float],
) -> Array:
    """Return ``(trace H)^2 - trace(H^2)``."""

    hxx, hyy, hzz, hxy, hxz, hyz = hessian_components(potential, spacing)
    trace = hxx + hyy + hzz
    hessian_square = (
        hxx**2 + hyy**2 + hzz**2 + 2.0 * (hxy**2 + hxz**2 + hyz**2)
    )
    return trace**2 - hessian_square


def cubic_hessian_operator(
    potential: Array,
    spacing: float | Sequence[float],
    *,
    kappa: float = 1.0,
) -> Array:
    """Apply the dimensionless v7C static operator."""

    coupling = float(kappa)
    if not np.isfinite(coupling) or coupling < 0.0:
        raise ValueError("kappa must be finite and non-negative")
    return 3.0 * laplacian(potential, spacing) + coupling * cubic_hessian_invariant(
        potential, spacing
    )


def ellipticity_eigenvalues(
    potential: Array,
    spacing: float | Sequence[float],
    *,
    kappa: float = 1.0,
) -> Array:
    """Return eigenvalues of the principal matrix on interior cells.

    Linearizing the equation gives
    ``Z_ij=3 delta_ij + 2 kappa[(trace H)delta_ij-H_ij]``.
    """

    coupling = float(kappa)
    if not np.isfinite(coupling) or coupling < 0.0:
        raise ValueError("kappa must be finite and non-negative")
    components = hessian_components(potential, spacing)
    hxx, hyy, hzz, hxy, hxz, hyz = (
        component[1:-1, 1:-1, 1:-1] for component in components
    )
    trace = hxx + hyy + hzz
    matrix = np.empty(hxx.shape + (3, 3), dtype=float)
    matrix[..., 0, 0] = 3.0 + 2.0 * coupling * (trace - hxx)
    matrix[..., 1, 1] = 3.0 + 2.0 * coupling * (trace - hyy)
    matrix[..., 2, 2] = 3.0 + 2.0 * coupling * (trace - hzz)
    matrix[..., 0, 1] = matrix[..., 1, 0] = -2.0 * coupling * hxy
    matrix[..., 0, 2] = matrix[..., 2, 0] = -2.0 * coupling * hxz
    matrix[..., 1, 2] = matrix[..., 2, 1] = -2.0 * coupling * hyz
    return np.linalg.eigvalsh(matrix)


def temporal_kinetic_coefficient(
    potential: Array,
    spacing: float | Sequence[float],
    *,
    kappa: float = 1.0,
) -> Array:
    """Return the time-derivative coefficient for perturbations on a static branch."""

    coupling = float(kappa)
    if not np.isfinite(coupling) or coupling < 0.0:
        raise ValueError("kappa must be finite and non-negative")
    return 3.0 + 2.0 * coupling * laplacian(potential, spacing)


def solve_cubic_hessian_dirichlet(
    source: Array,
    spacing: float | Sequence[float],
    boundary_potential: Array,
    *,
    kappa: float = 1.0,
    relaxation: float = 0.1,
    tolerance: float = 1.0e-7,
    max_iterations: int = 2000,
    initial_potential: Array | None = None,
) -> CubicHessianSolution:
    """Solve the cubic Hessian equation with damped Poisson Picard steps."""

    rhs = _validate_grid(source)
    boundary = _validate_grid(boundary_potential)
    if rhs.shape != boundary.shape:
        raise ValueError("source and boundary_potential must share a shape")
    coupling = float(kappa)
    damping = float(relaxation)
    target = float(tolerance)
    if not np.isfinite(coupling) or coupling < 0.0:
        raise ValueError("kappa must be finite and non-negative")
    if not np.isfinite(damping) or not 0.0 < damping <= 1.0:
        raise ValueError("relaxation must lie in (0,1]")
    if not np.isfinite(target) or target <= 0.0:
        raise ValueError("tolerance must be finite and positive")
    if int(max_iterations) <= 0:
        raise ValueError("max_iterations must be positive")

    if initial_potential is None:
        potential = solve_poisson_dirichlet(rhs / 3.0, spacing, boundary)
    else:
        potential = _validate_grid(initial_potential).copy()
        if potential.shape != rhs.shape:
            raise ValueError("initial_potential must share the source shape")
        mask = np.zeros(rhs.shape, dtype=bool)
        mask[[0, -1], :, :] = True
        mask[:, [0, -1], :] = True
        mask[:, :, [0, -1]] = True
        potential[mask] = boundary[mask]

    history: list[float] = []
    converged = False
    for _ in range(int(max_iterations)):
        nonlinear = cubic_hessian_invariant(potential, spacing)
        proposal = solve_poisson_dirichlet(
            (rhs - coupling * nonlinear) / 3.0,
            spacing,
            boundary,
        )
        potential = (1.0 - damping) * potential + damping * proposal
        residual = cubic_hessian_operator(potential, spacing, kappa=coupling) - rhs
        score = normalized_residual_rms(residual, rhs)
        history.append(score)
        if score <= target:
            converged = True
            break
        if not np.isfinite(score) or score > 1.0e12:
            break

    eigenvalues = ellipticity_eigenvalues(potential, spacing, kappa=coupling)
    temporal = temporal_kinetic_coefficient(potential, spacing, kappa=coupling)
    return CubicHessianSolution(
        potential=potential,
        residual_rms=float(history[-1]),
        converged=converged,
        iterations=len(history),
        minimum_temporal_kinetic_coefficient=float(
            np.min(temporal[1:-1, 1:-1, 1:-1])
        ),
        minimum_ellipticity_eigenvalue=float(np.min(eigenvalues)),
        residual_history=tuple(float(value) for value in history),
    )
