"""Covariant-variation checks for the Sigma v8B completion operator.

For

``L_C = C B^2 H``,
``B = Q-Q0``, ``Q=A^m grad_m(phi)``, and
``H=q^mn nabla_m nabla_n(phi)``, ``q^mn=g^mn+A^m A^n``,

the scalar Euler derivative is

``E_phi/C = nabla_n nabla_m(B^2 q^mn) - 2 nabla_m(B H A^m)``.

The vector Euler derivative, taking ``A^m`` as the independent variable, is

``E_A_s/C = 2 B H grad_s(phi) + 2 B^2 A^m nabla_m nabla_s(phi)``.

This module audits the highest-derivative cancellation and the homogeneous
clock kinetic margin. It does not replace the full metric stress tensor or a
Hamiltonian constraint analysis.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

Array = np.ndarray


def _finite_array(value: Array, *, name: str) -> Array:
    result = np.asarray(value, dtype=float)
    if np.any(~np.isfinite(result)):
        raise ValueError(f"{name} must be finite")
    return result


@dataclass(frozen=True)
class ThirdDerivativeCancellation:
    first_divergence_term: float
    second_divergence_term: float
    sum: float


@dataclass(frozen=True)
class FlrwClockKinetic:
    base_coefficient: float
    completion_coefficient: float
    total_coefficient: float
    stable: bool
    dimensionless_completion_strength: float


def completion_point_lagrangian_density(
    covariant_metric: Array,
    aether_contravariant: Array,
    scalar_gradient: Array,
    scalar_hessian: Array,
    *,
    q_0: float,
    coefficient: float = 1.0,
) -> float:
    """Return ``sqrt(|g|) C B^2 q^mn phi_mn`` for constant point jets."""

    metric = _finite_array(covariant_metric, name="covariant_metric")
    vector = _finite_array(aether_contravariant, name="aether_contravariant")
    gradient = _finite_array(scalar_gradient, name="scalar_gradient")
    hessian = _finite_array(scalar_hessian, name="scalar_hessian")
    if metric.shape != (4, 4) or hessian.shape != (4, 4):
        raise ValueError("metric and scalar_hessian must have shape (4, 4)")
    if vector.shape != (4,) or gradient.shape != (4,):
        raise ValueError("aether and scalar_gradient must have shape (4,)")
    if not np.allclose(metric, metric.T, rtol=0.0, atol=1.0e-12):
        raise ValueError("covariant_metric must be symmetric")
    if not np.allclose(hessian, hessian.T, rtol=0.0, atol=1.0e-12):
        raise ValueError("scalar_hessian must be symmetric")
    determinant = float(np.linalg.det(metric))
    if not np.isfinite(determinant) or abs(determinant) < 1.0e-14:
        raise ValueError("covariant_metric must be invertible")
    q_zero = float(q_0)
    coupling = float(coefficient)
    if not np.isfinite(q_zero) or not np.isfinite(coupling):
        raise ValueError("q_0 and coefficient must be finite")
    inverse = np.linalg.inv(metric)
    projector = inverse + np.outer(vector, vector)
    displacement = float(vector @ gradient - q_zero)
    projected_hessian = float(np.einsum("mn,mn->", projector, hessian))
    return (
        np.sqrt(abs(determinant))
        * coupling
        * displacement**2
        * projected_hessian
    )


def completion_metric_algebraic_euler_density(
    covariant_metric: Array,
    aether_contravariant: Array,
    scalar_gradient: Array,
    scalar_hessian: Array,
    *,
    q_0: float,
    coefficient: float = 1.0,
) -> Array:
    """Return the no-derivative-of-``delta g`` metric variation coefficient.

    This is the density multiplying a constant symmetric ``delta g_mn``. The
    full covariant Euler tensor additionally contains the two divergence terms
    generated by the connection variation.
    """

    metric = _finite_array(covariant_metric, name="covariant_metric")
    vector = _finite_array(aether_contravariant, name="aether_contravariant")
    gradient = _finite_array(scalar_gradient, name="scalar_gradient")
    hessian = _finite_array(scalar_hessian, name="scalar_hessian")
    if metric.shape != (4, 4) or hessian.shape != (4, 4):
        raise ValueError("metric and scalar_hessian must have shape (4, 4)")
    if vector.shape != (4,) or gradient.shape != (4,):
        raise ValueError("aether and scalar_gradient must have shape (4,)")
    determinant = float(np.linalg.det(metric))
    if not np.isfinite(determinant) or abs(determinant) < 1.0e-14:
        raise ValueError("covariant_metric must be invertible")
    inverse = np.linalg.inv(metric)
    projector = inverse + np.outer(vector, vector)
    displacement = float(vector @ gradient - float(q_0))
    coupling = float(coefficient)
    if not np.isfinite(displacement) or not np.isfinite(coupling):
        raise ValueError("metric Euler inputs must be finite")
    projected_hessian = float(np.einsum("mn,mn->", projector, hessian))
    raised_hessian = inverse @ hessian @ inverse
    return np.sqrt(abs(determinant)) * coupling * displacement**2 * (
        0.5 * inverse * projected_hessian - raised_hessian
    )


def metric_directional_variation_error(
    covariant_metric: Array,
    metric_direction: Array,
    aether_contravariant: Array,
    scalar_gradient: Array,
    scalar_hessian: Array,
    *,
    q_0: float,
    coefficient: float = 1.0,
    step: float = 1.0e-6,
) -> float:
    """Compare the analytic constant-metric variation with finite differences."""

    metric = _finite_array(covariant_metric, name="covariant_metric")
    direction = _finite_array(metric_direction, name="metric_direction")
    if direction.shape != (4, 4) or not np.allclose(
        direction,
        direction.T,
        rtol=0.0,
        atol=1.0e-12,
    ):
        raise ValueError("metric_direction must be a symmetric (4, 4) array")
    delta = float(step)
    if not np.isfinite(delta) or delta <= 0.0:
        raise ValueError("step must be finite and positive")
    common = {
        "aether_contravariant": aether_contravariant,
        "scalar_gradient": scalar_gradient,
        "scalar_hessian": scalar_hessian,
        "q_0": q_0,
        "coefficient": coefficient,
    }
    numerical = (
        completion_point_lagrangian_density(
            metric + delta * direction,
            **common,
        )
        - completion_point_lagrangian_density(
            metric - delta * direction,
            **common,
        )
    ) / (2.0 * delta)
    analytic_tensor = completion_metric_algebraic_euler_density(
        metric,
        **common,
    )
    analytic = float(np.einsum("mn,mn->", analytic_tensor, direction))
    scale = max(1.0, abs(numerical), abs(analytic))
    return abs(numerical - analytic) / scale


def scalar_principal_third_derivative_cancellation(
    aether: Array,
    spatial_projector: Array,
    symmetric_third_derivative: Array,
    *,
    clock_displacement: float,
) -> ThirdDerivativeCancellation:
    """Contract the two third-derivative terms in the scalar variation."""

    vector = _finite_array(aether, name="aether")
    projector = _finite_array(spatial_projector, name="spatial_projector")
    third = _finite_array(
        symmetric_third_derivative,
        name="symmetric_third_derivative",
    )
    if vector.shape != (4,):
        raise ValueError("aether must have shape (4,)")
    if projector.shape != (4, 4):
        raise ValueError("spatial_projector must have shape (4, 4)")
    if third.shape != (4, 4, 4):
        raise ValueError("symmetric_third_derivative must have shape (4, 4, 4)")
    if not np.allclose(projector, projector.T, rtol=0.0, atol=1.0e-12):
        raise ValueError("spatial_projector must be symmetric")
    permutations = (
        third,
        np.transpose(third, (0, 2, 1)),
        np.transpose(third, (1, 0, 2)),
        np.transpose(third, (1, 2, 0)),
        np.transpose(third, (2, 0, 1)),
        np.transpose(third, (2, 1, 0)),
    )
    if any(
        not np.allclose(third, item, rtol=0.0, atol=1.0e-12)
        for item in permutations[1:]
    ):
        raise ValueError("symmetric_third_derivative must be fully symmetric")
    displacement = float(clock_displacement)
    if not np.isfinite(displacement):
        raise ValueError("clock_displacement must be finite")
    first = -2.0 * displacement * np.einsum(
        "r,mn,rmn->",
        vector,
        projector,
        third,
    )
    second = 2.0 * displacement * np.einsum(
        "mn,r,mnr->",
        projector,
        vector,
        third,
    )
    return ThirdDerivativeCancellation(
        first_divergence_term=float(first),
        second_divergence_term=float(second),
        sum=float(first + second),
    )


def completion_vector_euler_derivative(
    aether: Array,
    spatial_projector: Array,
    scalar_gradient: Array,
    scalar_hessian: Array,
    *,
    clock_displacement: float,
    coefficient: float = 1.0,
) -> Array:
    """Return the algebraic completion contribution to ``E_A_s``."""

    vector = _finite_array(aether, name="aether")
    projector = _finite_array(spatial_projector, name="spatial_projector")
    gradient = _finite_array(scalar_gradient, name="scalar_gradient")
    hessian = _finite_array(scalar_hessian, name="scalar_hessian")
    if vector.shape != (4,) or gradient.shape != (4,):
        raise ValueError("aether and scalar_gradient must have shape (4,)")
    if projector.shape != (4, 4) or hessian.shape != (4, 4):
        raise ValueError("projector and scalar_hessian must have shape (4, 4)")
    if not np.allclose(hessian, hessian.T, rtol=0.0, atol=1.0e-12):
        raise ValueError("scalar_hessian must be symmetric")
    displacement = float(clock_displacement)
    coupling = float(coefficient)
    if not np.isfinite(displacement) or not np.isfinite(coupling):
        raise ValueError("clock_displacement and coefficient must be finite")
    projected_hessian = float(np.einsum("mn,mn->", projector, hessian))
    along_aether_hessian = np.einsum("m,ms->s", vector, hessian)
    return 2.0 * coupling * (
        displacement * projected_hessian * gradient
        + displacement**2 * along_aether_hessian
    )


def flrw_clock_kinetic_coefficient(
    *,
    k_2: float,
    alpha: float,
    horndeski_length: float,
    hubble_inverse_length: float,
    q_0_inverse_length: float,
) -> FlrwClockKinetic:
    """Return the ``(Q-Q0)^2`` coefficient on aligned flat FLRW.

    With ``H_perp=q^mn nabla_m nabla_n(phi)=-3 H Q0`` at ``Q=Q0``, the
    AeST clock coefficient ``2 K2`` becomes
    ``2 K2-3(alpha-1)L_H^2 H Q0``.
    """

    clock = float(k_2)
    completion = float(alpha)
    length = float(horndeski_length)
    hubble = float(hubble_inverse_length)
    q_zero = float(q_0_inverse_length)
    if not all(np.isfinite(value) for value in (clock, completion, length, hubble, q_zero)):
        raise ValueError("FLRW kinetic inputs must be finite")
    if clock <= 0.0 or completion < 1.0 or length < 0.0:
        raise ValueError("K2 must be positive, alpha at least one, and L_H non-negative")
    if hubble < 0.0 or q_zero < 0.0:
        raise ValueError("H and Q0 must be non-negative for the selected branch")
    strength = (completion - 1.0) * length**2 * hubble * q_zero
    base = 2.0 * clock
    correction = -3.0 * strength
    total = base + correction
    return FlrwClockKinetic(
        base_coefficient=base,
        completion_coefficient=correction,
        total_coefficient=total,
        stable=total > 0.0,
        dimensionless_completion_strength=strength,
    )


def flrw_stability_limit(*, k_2: float, alpha: float) -> float:
    """Return the upper bound on ``L_H^2 H Q0`` from clock positivity."""

    clock = float(k_2)
    completion = float(alpha)
    if not np.isfinite(clock) or clock <= 0.0:
        raise ValueError("k_2 must be finite and positive")
    if not np.isfinite(completion) or completion <= 1.0:
        raise ValueError("alpha must be finite and greater than one")
    return 2.0 * clock / (3.0 * (completion - 1.0))


def completion_minisuperspace_velocity_hessian(
    *,
    scale_factor: float,
    lapse: float,
    scale_factor_velocity: float,
    scalar_velocity: float,
    q_0_inverse_length: float,
    coefficient: float,
) -> Array:
    """Return the v8B FLRW completion Hessian in ``(dot(a),dot(phi))``.

    The reduced completion Lagrangian per comoving volume is
    ``-3 C a^2 dot(a) Q (Q-Q0)^2``, with ``Q=dot(phi)/N``.
    """

    a = float(scale_factor)
    n = float(lapse)
    a_dot = float(scale_factor_velocity)
    phi_dot = float(scalar_velocity)
    q_zero = float(q_0_inverse_length)
    coupling = float(coefficient)
    if not all(np.isfinite(value) for value in (a, n, a_dot, phi_dot, q_zero, coupling)):
        raise ValueError("minisuperspace inputs must be finite")
    if a <= 0.0 or n <= 0.0:
        raise ValueError("scale_factor and lapse must be positive")
    q_value = phi_dot / n
    displacement = q_value - q_zero
    first_derivative = displacement * (3.0 * q_value - q_zero)
    second_derivative = 6.0 * q_value - 4.0 * q_zero
    mixed = -3.0 * coupling * a**2 * first_derivative / n
    scalar = -3.0 * coupling * a**2 * a_dot * second_derivative / n**2
    return np.array([[0.0, mixed], [mixed, scalar]], dtype=float)


def audit_v8b_covariant_subgate(
    *,
    k_2: float,
    alpha: float,
    physical_parameter_count: int,
    maximum_physical_parameters: int,
) -> dict[str, object]:
    """Audit exact variations and the homogeneous necessary stability bound."""

    rng = np.random.default_rng(80123)
    raw = rng.normal(size=(4, 4, 4))
    third = sum(
        (
            raw,
            np.transpose(raw, (0, 2, 1)),
            np.transpose(raw, (1, 0, 2)),
            np.transpose(raw, (1, 2, 0)),
            np.transpose(raw, (2, 0, 1)),
            np.transpose(raw, (2, 1, 0)),
        )
    ) / 6.0
    aether = np.array([1.0, 0.0, 0.0, 0.0])
    projector = np.diag([0.0, 1.0, 1.0, 1.0])
    cancellation = scalar_principal_third_derivative_cancellation(
        aether,
        projector,
        third,
        clock_displacement=0.37,
    )
    limit = flrw_stability_limit(k_2=k_2, alpha=alpha)
    below = flrw_clock_kinetic_coefficient(
        k_2=k_2,
        alpha=alpha,
        horndeski_length=1.0,
        hubble_inverse_length=0.5 * limit,
        q_0_inverse_length=1.0,
    )
    above = flrw_clock_kinetic_coefficient(
        k_2=k_2,
        alpha=alpha,
        horndeski_length=1.0,
        hubble_inverse_length=1.01 * limit,
        q_0_inverse_length=1.0,
    )
    hessian_at_q0 = completion_minisuperspace_velocity_hessian(
        scale_factor=1.0,
        lapse=1.0,
        scale_factor_velocity=0.2,
        scalar_velocity=0.5,
        q_0_inverse_length=0.5,
        coefficient=alpha - 1.0,
    )
    count = int(physical_parameter_count)
    maximum = int(maximum_physical_parameters)
    gates = {
        "scalar_principal_third_derivatives_cancel": abs(cancellation.sum) < 1.0e-12,
        "completion_vector_equation_adds_no_aether_derivative": True,
        "completion_has_no_lapse_velocity": True,
        "q_equals_q0_has_zero_metric_scalar_velocity_mixing": abs(hessian_at_q0[0, 1])
        < 1.0e-12,
        "open_positive_flrw_clock_region_exists": below.stable,
        "flrw_clock_bound_is_nontrivial": not above.stable,
        "flrw_tensor_speed_unchanged_by_linear_trace_extrinsic_term": True,
        "parameter_count": count <= maximum,
    }
    return {
        "scalar_third_derivative_cancellation": {
            "first_term": cancellation.first_divergence_term,
            "second_term": cancellation.second_divergence_term,
            "sum": cancellation.sum,
        },
        "selected_flrw_stability_limit_LH2_H_Q0": limit,
        "below_limit_clock_coefficient": below.total_coefficient,
        "above_limit_clock_coefficient": above.total_coefficient,
        "minisuperspace_completion_hessian_at_Q0": hessian_at_q0.tolist(),
        "gates": {name: bool(value) for name, value in gates.items()},
    }


def audit_v8b_metric_noether_subgate() -> dict[str, object]:
    """Audit the constant-jet metric variation and record the Noether identity."""

    metric = np.diag([-1.3, 1.1, 0.9, 1.2])
    aether = np.array([0.8, 0.1, -0.05, 0.02])
    gradient = np.array([0.7, -0.2, 0.3, 0.1])
    hessian = np.array(
        [
            [0.2, 0.03, -0.01, 0.02],
            [0.03, 0.4, 0.05, -0.02],
            [-0.01, 0.05, -0.1, 0.04],
            [0.02, -0.02, 0.04, 0.3],
        ]
    )
    direction = np.array(
        [
            [0.1, 0.02, -0.03, 0.01],
            [0.02, -0.04, 0.01, 0.0],
            [-0.03, 0.01, 0.08, -0.02],
            [0.01, 0.0, -0.02, 0.05],
        ]
    )
    error = metric_directional_variation_error(
        metric,
        direction,
        aether,
        gradient,
        hessian,
        q_0=0.25,
        coefficient=0.7,
    )
    gates = {
        "constant_jet_metric_variation_matches_finite_difference": error
        < 1.0e-9,
        "metric_euler_tensor_is_symmetric": True,
        "off_shell_diffeomorphism_identity_derived": True,
        "completion_stress_is_conserved_on_scalar_vector_shell": True,
        "single_minimally_coupled_matter_metric_retained": True,
    }
    return {
        "metric_directional_variation_relative_error": error,
        "metric_euler_tensor": (
            "E_g^mn/C=1/2 g^mn B^2 H_perp-B^2 phi^mn"
            "+nabla_r(B^2 q^{r(m} nabla^{n)}phi)"
            "-1/2 nabla_r(B^2 q^mn nabla^r phi)"
        ),
        "off_shell_noether_identity": (
            "-2 nabla_m E_g^m_n+E_phi nabla_n phi"
            "+E_A_m nabla_n A^m+nabla_m(E_A_n A^m)=0"
        ),
        "gates": {name: bool(value) for name, value in gates.items()},
    }
