#!/usr/bin/env python3
"""
CMB Power Spectrum in Coherence Cosmology
==========================================

The CMB power spectrum is the critical test. We need to explain:
1. The acoustic peaks at l ~ 220, 540, 810
2. The peak height ratios
3. The damping tail
4. The overall amplitude

In ΛCDM, these come from baryon-photon acoustic oscillations.
In coherence cosmology, we need a different mechanism.

Author: Sigma Gravity Research
Date: December 2025
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad, odeint
from scipy.interpolate import interp1d

print("=" * 100)
print("CMB POWER SPECTRUM IN COHERENCE COSMOLOGY")
print("=" * 100)

# =============================================================================
# PHYSICAL CONSTANTS
# =============================================================================

c = 3e8            # m/s
H0 = 2.27e-18      # s⁻¹ (73 km/s/Mpc)
G = 6.674e-11      # m³/kg/s²
k_B = 1.381e-23    # J/K
hbar = 1.055e-34   # J·s
T0 = 2.725         # K (CMB temperature today)

# Derived quantities
rho_crit = 3 * H0**2 / (8 * np.pi * G)  # kg/m³
L_H = c / H0       # Hubble radius in m
L_H_Mpc = L_H / 3.086e22  # Hubble radius in Mpc

print(f"""
Physical Constants:
  H₀ = {H0:.3e} s⁻¹ = 73 km/s/Mpc
  ρ_crit = {rho_crit:.3e} kg/m³
  L_H = {L_H:.3e} m = {L_H_Mpc:.0f} Mpc
  T₀ = {T0} K
""")

# =============================================================================
# PART 1: THE ΛCDM PICTURE (FOR REFERENCE)
# =============================================================================

print("""
================================================================================
PART 1: THE ΛCDM PICTURE (FOR REFERENCE)
================================================================================

In ΛCDM, the CMB power spectrum arises from:

1. PRIMORDIAL FLUCTUATIONS
   - Inflation creates nearly scale-invariant density perturbations
   - Power spectrum: P(k) ∝ k^{n_s-1} with n_s ≈ 0.965

2. ACOUSTIC OSCILLATIONS
   - Before recombination (z > 1100):
     * Baryons and photons tightly coupled
     * Gravity pulls matter into potential wells
     * Radiation pressure pushes back
     * Sound waves with c_s = c/√3
   
3. RECOMBINATION (z ~ 1100)
   - Electrons combine with protons → neutral hydrogen
   - Photons decouple and free-stream
   - Oscillation pattern "frozen in"

4. PEAK STRUCTURE
   - First peak: Mode that reached maximum compression
   - Second peak: Mode that reached maximum rarefaction
   - Third peak: Mode that completed 1.5 oscillations
   - Peak positions: l_n ≈ n × π × d_A / r_s
     where r_s ~ 150 Mpc is the sound horizon

5. PEAK HEIGHTS
   - Odd peaks (1, 3, 5): Enhanced by baryon loading
   - Even peaks (2, 4, 6): Suppressed by baryon loading
   - Third peak: Boosted by dark matter potential wells

6. DAMPING TAIL
   - Silk damping from photon diffusion
   - Exponential suppression at l > 1000
""")

# =============================================================================
# PART 2: THE CHALLENGE FOR COHERENCE COSMOLOGY
# =============================================================================

print("""
================================================================================
PART 2: THE CHALLENGE FOR COHERENCE COSMOLOGY
================================================================================

In coherence cosmology:
- The universe is static (no expansion)
- The CMB is generated by the coherence field
- T_coh(z) = T₀(1+z) is maintained by the coherence field

KEY QUESTIONS:
1. What creates the temperature fluctuations ΔT/T ~ 10⁻⁵?
2. What sets the angular scale of the peaks?
3. What determines the peak height ratios?
4. How does the damping tail arise?

POSSIBLE APPROACHES:

APPROACH A: COHERENCE FIELD FLUCTUATIONS
----------------------------------------
The coherence field φ has spatial variations:
    φ(x) = φ̄ + δφ(x)

These create temperature variations:
    δT/T = f(δφ/φ̄)

The power spectrum of δφ sets the CMB power spectrum.

APPROACH B: MATTER-COHERENCE COUPLING
-------------------------------------
Matter density fluctuations create coherence fluctuations:
    δφ ∝ δρ

The matter power spectrum P_δ(k) is imprinted on the CMB.

APPROACH C: COHERENCE FIELD OSCILLATIONS
----------------------------------------
The coherence field might support oscillations:
    □φ + m²φ = 0

Standing waves in the coherence field create temperature patterns.

Let's develop APPROACH B, which is most promising.
""")

# =============================================================================
# PART 3: MATTER-COHERENCE COUPLING
# =============================================================================

print("""
================================================================================
PART 3: MATTER-COHERENCE COUPLING
================================================================================

From our Lagrangian:
    L_int = λ φ [j² - ℓ²(∇j)²] / j₀²

The coherence field is sourced by matter:
    ∇²φ - m²(g)φ = λ j² / j₀²

For cosmological perturbations:
    j² = ρ² v² ≈ ρ̄² v̄² (1 + 2δ)

where δ = δρ/ρ̄ is the density contrast.

The coherence field perturbation is:
    δφ ∝ δ

The CMB temperature is:
    T_coh = T₀ (1 + 2Ψ_coh)

where Ψ_coh = αφ/M_P².

Temperature fluctuations:
    δT/T = 2 δΨ_coh = 2α δφ / M_P²

So:
    δT/T ∝ δ

The CMB power spectrum traces the matter power spectrum!
""")

# =============================================================================
# PART 4: THE MATTER POWER SPECTRUM
# =============================================================================

print("""
================================================================================
PART 4: THE MATTER POWER SPECTRUM
================================================================================

The matter power spectrum P(k) has been measured precisely.
Key features:
- Turnover at k ~ 0.01 h/Mpc (~ 100 Mpc scale)
- BAO wiggles at k ~ 0.1 h/Mpc (~ 150 Mpc scale)
- Power law at small scales: P(k) ∝ k^{-3} (Silk damping)

In coherence cosmology, if δT/T ∝ δ, then:
    C_l^{TT} ∝ ∫ P(k) |W_l(k)|² dk

where W_l(k) is a window function relating k to l.

The angular scale l corresponds to physical scale:
    k = l / d_A

where d_A is the angular diameter distance to the "CMB surface."

QUESTION: What is the "CMB surface" in coherence cosmology?
""")

# =============================================================================
# PART 5: THE CMB SURFACE IN COHERENCE COSMOLOGY
# =============================================================================

print("""
================================================================================
PART 5: THE CMB SURFACE IN COHERENCE COSMOLOGY
================================================================================

In ΛCDM, the CMB comes from the "surface of last scattering" at z ~ 1100.

In coherence cosmology, the CMB is generated EVERYWHERE by the coherence field.
There's no single "surface."

However, we can define an EFFECTIVE surface:

OPTION 1: OPTICAL DEPTH SURFACE
-------------------------------
At high z, the universe becomes opaque due to:
- Free electrons (if ionized)
- Coherence field absorption

Define z_* where optical depth τ = 1.
Photons from z > z_* are absorbed/scattered.
We effectively see the CMB from z ~ z_*.

OPTION 2: COHERENCE SATURATION
------------------------------
The coherence potential grows with distance:
    Ψ_coh = H₀ d / (2c) = z/2

At some z_sat, the coherence field "saturates" and the
CMB temperature stops increasing.

OPTION 3: MATTER DISTRIBUTION
-----------------------------
The CMB fluctuations trace matter fluctuations.
The effective "surface" is where most of the matter is.

For a uniform matter distribution, there's no preferred surface.
But structure (galaxies, clusters) is concentrated at z < 3.

The CMB we see is dominated by nearby structure!

Let's explore OPTION 3.
""")

# =============================================================================
# PART 6: CMB FROM NEARBY STRUCTURE
# =============================================================================

print("""
================================================================================
PART 6: CMB FROM NEARBY STRUCTURE
================================================================================

HYPOTHESIS:
The CMB fluctuations we observe come from the coherence field's
response to NEARBY matter structure (z < 3).

The temperature fluctuation at angular position θ is:
    δT(θ)/T = ∫₀^∞ W(z) δ_coh(θ, z) dz

where:
- W(z) is a weighting function (how much each z contributes)
- δ_coh(θ, z) is the coherence fluctuation at position (θ, z)

For matter-sourced coherence:
    δ_coh ∝ δ_matter

The CMB power spectrum is:
    C_l = ∫₀^∞ W(z)² P(k=l/d_A(z), z) dz

WHAT SETS W(z)?
---------------
Several possibilities:

1. Uniform weighting: W(z) = const
   - All distances contribute equally
   - Dominated by nearby structure (more volume)

2. Coherence weighting: W(z) ∝ T_coh(z) = T₀(1+z)
   - Higher z contributes more (hotter CMB)
   - But also more redshifted

3. Matter weighting: W(z) ∝ ρ_matter(z)
   - More matter → more coherence source
   - In static universe: ρ = const
   - But structure is concentrated at low z

Let's compute the power spectrum for different W(z).
""")

# =============================================================================
# PART 7: COMPUTING THE POWER SPECTRUM
# =============================================================================

print("""
================================================================================
PART 7: COMPUTING THE POWER SPECTRUM
================================================================================
""")

# Matter power spectrum (simplified model)
def matter_power_spectrum(k):
    """
    Simplified matter power spectrum P(k).
    
    k in h/Mpc
    Returns P(k) in (Mpc/h)³
    """
    # Normalization
    A_s = 2.1e-9  # Amplitude
    n_s = 0.965   # Spectral index
    k_pivot = 0.05  # h/Mpc
    
    # Transfer function (simplified Eisenstein-Hu)
    k_eq = 0.01  # h/Mpc (matter-radiation equality)
    
    # Shape
    T_k = 1 / (1 + (k / k_eq)**2)**0.5
    
    # BAO wiggles (simplified)
    k_BAO = 0.1  # h/Mpc
    A_BAO = 0.1  # Amplitude of wiggles
    T_k *= (1 + A_BAO * np.sin(k / k_BAO * np.pi))
    
    # Primordial + transfer
    P_k = A_s * (k / k_pivot)**(n_s - 1) * T_k**2
    
    # Normalize to σ₈ ~ 0.8
    P_k *= 1e10  # Rough normalization
    
    return P_k

# Angular diameter distance in coherence cosmology
def d_A_coherence(z, H0_kmsMpc=73, alpha=1.4, beta=-0.4):
    """
    Angular diameter distance in coherence cosmology.
    
    d_A = d_L / (1+z)^{2+β}
    """
    c_kms = 3e5  # km/s
    d_L = (c_kms / H0_kmsMpc) * ((1 + z)**alpha - 1) / alpha
    d_A = d_L / (1 + z)**(2 + beta)
    return d_A  # Mpc

# Window function
def window_function(z, model='uniform'):
    """
    Weighting function W(z).
    """
    if model == 'uniform':
        return 1.0
    elif model == 'coherence':
        return 1 + z
    elif model == 'gaussian':
        z_peak = 1.0
        sigma_z = 0.5
        return np.exp(-(z - z_peak)**2 / (2 * sigma_z**2))
    elif model == 'lcdm_like':
        # Peaked at z ~ 1100 (but we'll use z ~ 2 for illustration)
        z_peak = 2.0
        sigma_z = 0.3
        return np.exp(-(z - z_peak)**2 / (2 * sigma_z**2))
    else:
        return 1.0

# Compute C_l
def compute_Cl(l_array, W_model='uniform', z_max=5.0, n_z=100):
    """
    Compute CMB power spectrum C_l.
    
    C_l = ∫ W(z)² P(k=l/d_A(z)) / d_A(z)² dz
    """
    z_array = np.linspace(0.01, z_max, n_z)
    
    C_l = np.zeros_like(l_array, dtype=float)
    
    for i, l in enumerate(l_array):
        integrand = 0
        for z in z_array:
            d_A = d_A_coherence(z)
            if d_A > 0:
                k = l / d_A  # h/Mpc (assuming d_A in Mpc/h)
                k = k * 0.7  # Convert to h/Mpc with h=0.7
                if k > 1e-4 and k < 10:
                    W = window_function(z, W_model)
                    P_k = matter_power_spectrum(k)
                    integrand += W**2 * P_k / d_A**2
        
        C_l[i] = integrand * (z_array[1] - z_array[0])
    
    # Normalize to match observed amplitude
    C_l_normalized = C_l / np.max(C_l) * 6000  # μK²
    
    return C_l_normalized

# Compute for different models
l_array = np.logspace(1, 3.5, 200)

print("Computing C_l for different window functions...")
Cl_uniform = compute_Cl(l_array, W_model='uniform')
Cl_coherence = compute_Cl(l_array, W_model='coherence')
Cl_gaussian = compute_Cl(l_array, W_model='gaussian')
Cl_lcdm_like = compute_Cl(l_array, W_model='lcdm_like')

# =============================================================================
# PART 8: COMPARISON WITH OBSERVATIONS
# =============================================================================

print("""
================================================================================
PART 8: COMPARISON WITH OBSERVATIONS
================================================================================
""")

# Planck 2018 data (approximate peak positions and heights)
l_planck = np.array([220, 540, 810, 1120, 1420])
Cl_planck = np.array([5800, 2500, 2800, 1800, 1200])  # μK²
Cl_planck_err = np.array([100, 100, 100, 100, 100])

# Create figure
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: All models
ax1 = axes[0, 0]
ax1.semilogy(l_array, Cl_uniform, 'b-', linewidth=2, label='Uniform W(z)')
ax1.semilogy(l_array, Cl_coherence, 'g-', linewidth=2, label='Coherence W(z) ∝ (1+z)')
ax1.semilogy(l_array, Cl_gaussian, 'r-', linewidth=2, label='Gaussian W(z), z_peak=1')
ax1.semilogy(l_array, Cl_lcdm_like, 'm-', linewidth=2, label='ΛCDM-like W(z), z_peak=2')
ax1.errorbar(l_planck, Cl_planck, yerr=Cl_planck_err, fmt='ko', markersize=8, label='Planck 2018')
ax1.set_xlabel('Multipole l')
ax1.set_ylabel('$l(l+1)C_l/2\\pi$ [μK²]')
ax1.set_title('CMB Power Spectrum: Different Window Functions')
ax1.legend(fontsize=8)
ax1.set_xlim(10, 3000)
ax1.set_ylim(100, 10000)
ax1.grid(True, alpha=0.3)

# Plot 2: Best model vs Planck
ax2 = axes[0, 1]
ax2.semilogy(l_array, Cl_lcdm_like, 'b-', linewidth=2, label='Coherence (z_peak=2)')
ax2.errorbar(l_planck, Cl_planck, yerr=Cl_planck_err, fmt='ko', markersize=8, label='Planck 2018')
ax2.set_xlabel('Multipole l')
ax2.set_ylabel('$l(l+1)C_l/2\\pi$ [μK²]')
ax2.set_title('Best Coherence Model vs Planck')
ax2.legend()
ax2.set_xlim(10, 3000)
ax2.set_ylim(100, 10000)
ax2.grid(True, alpha=0.3)

# Plot 3: Matter power spectrum
ax3 = axes[1, 0]
k_array = np.logspace(-3, 1, 200)
P_k = [matter_power_spectrum(k) for k in k_array]
ax3.loglog(k_array, P_k, 'b-', linewidth=2)
ax3.axvline(0.01, color='r', linestyle='--', label='k_eq ~ 0.01 h/Mpc')
ax3.axvline(0.1, color='g', linestyle='--', label='k_BAO ~ 0.1 h/Mpc')
ax3.set_xlabel('k [h/Mpc]')
ax3.set_ylabel('P(k) [(Mpc/h)³]')
ax3.set_title('Matter Power Spectrum (simplified)')
ax3.legend()
ax3.grid(True, alpha=0.3)

# Plot 4: Angular diameter distance
ax4 = axes[1, 1]
z_plot = np.linspace(0.01, 5, 100)
d_A_plot = [d_A_coherence(z) for z in z_plot]
ax4.plot(z_plot, d_A_plot, 'b-', linewidth=2, label='Coherence')
# ΛCDM for comparison (simplified)
d_A_lcdm = [3000 * z / (1 + z)**0.5 for z in z_plot]  # Very rough
ax4.plot(z_plot, d_A_lcdm, 'r--', linewidth=2, label='ΛCDM (approx)')
ax4.set_xlabel('Redshift z')
ax4.set_ylabel('$d_A$ [Mpc]')
ax4.set_title('Angular Diameter Distance')
ax4.legend()
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/Users/leonardspeiser/Projects/sigmagravity/current/derivations/cmb_power_spectrum.png', dpi=150)
print("Saved figure to cmb_power_spectrum.png")

# =============================================================================
# PART 9: THE ACOUSTIC PEAK PROBLEM
# =============================================================================

print("""
================================================================================
PART 9: THE ACOUSTIC PEAK PROBLEM
================================================================================

OBSERVATION:
The CMB has sharp acoustic peaks at l ~ 220, 540, 810.
These are NOT present in our simple matter-sourced model.

WHY THE PEAKS ARE MISSING:
--------------------------
In our model, C_l traces the matter power spectrum P(k).
The matter power spectrum has:
- A broad turnover at k ~ 0.01 h/Mpc
- Weak BAO wiggles at k ~ 0.1 h/Mpc

This gives a SMOOTH C_l, not sharp peaks.

WHAT'S NEEDED FOR PEAKS:
------------------------
Sharp peaks require OSCILLATIONS in the source.
In ΛCDM, these come from baryon-photon acoustic oscillations.

In coherence cosmology, we need a different oscillation mechanism.

POSSIBLE SOLUTIONS:

SOLUTION 1: COHERENCE FIELD OSCILLATIONS
----------------------------------------
The coherence field might support standing waves:
    □φ + m²φ = 0

With boundary conditions (e.g., at the Hubble horizon),
this gives discrete modes:
    k_n = n π / L_H

These would create peaks at:
    l_n = k_n × d_A = n π d_A / L_H

For d_A ~ 4000 Mpc and L_H ~ 4000 Mpc:
    l_n ~ n π ~ 3, 6, 9, ...

This is WAY too small. The first peak should be at l ~ 220.

SOLUTION 2: BAO-INDUCED PEAKS
-----------------------------
The BAO feature in the matter power spectrum is at k ~ 0.1 h/Mpc.
This corresponds to the sound horizon r_s ~ 150 Mpc.

If the CMB traces matter fluctuations, BAO should appear.
But BAO wiggles are weak (~ 10% amplitude), not sharp peaks.

To get sharp peaks, we need to AMPLIFY the BAO.

SOLUTION 3: RESONANT AMPLIFICATION
----------------------------------
The coherence field might resonate with the BAO scale.

If the coherence field has a characteristic frequency:
    ω_coh = m_0 c² / ℏ ~ H_0

And the BAO has a characteristic scale:
    k_BAO ~ 0.1 h/Mpc

Resonance occurs when:
    ω_coh / c = k_BAO

This could amplify the BAO wiggles into sharp peaks.
""")

# =============================================================================
# PART 10: COHERENCE FIELD OSCILLATIONS
# =============================================================================

print("""
================================================================================
PART 10: COHERENCE FIELD OSCILLATIONS
================================================================================

Let's explore whether the coherence field can produce acoustic-like oscillations.

THE COHERENCE FIELD EQUATION:
-----------------------------
From our Lagrangian:
    □φ + m²(g)φ = S(x)

where S(x) is the matter source.

For cosmological perturbations:
    φ = φ̄ + δφ
    
    □(δφ) + m²(δφ) = δS

If m² > 0, this is a MASSIVE field equation.
Solutions are damped oscillations, not standing waves.

If m² < 0 (tachyonic), solutions grow exponentially.
This is unstable.

For m² = 0 (massless), solutions are waves:
    δφ ∝ e^{i(kx - ωt)} with ω = ck

COUPLED OSCILLATIONS:
---------------------
The coherence field couples to matter:
    □φ + m²φ = λ ρ

Matter responds to the coherence field:
    ∂²δ/∂t² + ... = -∇²Φ_eff = -∇²(Φ_N + αφ)

This is a COUPLED system:
    □φ = -m²φ + λρ
    ∂²δ/∂t² = -k²(Φ_N + αφ)

The coupled system can have oscillatory solutions!

DISPERSION RELATION:
--------------------
For plane waves δ, φ ∝ e^{i(kx - ωt)}:

    -ω² φ + k² φ + m² φ = λ ρ̄ δ
    -ω² δ = -k² (4πGρ̄/k² δ + α φ)

Simplifying:
    (k² + m² - ω²) φ = λ ρ̄ δ
    ω² δ = 4πGρ̄ δ + α k² φ

Substituting:
    ω² = 4πGρ̄ + α k² λ ρ̄ / (k² + m² - ω²)

This is a quadratic in ω²:
    ω²(k² + m² - ω²) = 4πGρ̄(k² + m² - ω²) + αλρ̄ k²

    ω⁴ - ω²(k² + m² + 4πGρ̄) + 4πGρ̄(k² + m²) - αλρ̄ k² = 0

The solutions ω²(k) give the dispersion relation.
""")

# Compute dispersion relation
def dispersion_relation(k, m, alpha_lambda_rho):
    """
    Solve for ω² from the coupled coherence-matter system.
    """
    G_rho = 4 * np.pi * G * rho_crit  # 4πGρ
    
    # Coefficients of ω⁴ - b ω² + c = 0
    b = k**2 + m**2 + G_rho
    c = G_rho * (k**2 + m**2) - alpha_lambda_rho * k**2
    
    # Solutions
    discriminant = b**2 - 4*c
    if discriminant < 0:
        return None, None
    
    omega_sq_plus = (b + np.sqrt(discriminant)) / 2
    omega_sq_minus = (b - np.sqrt(discriminant)) / 2
    
    return omega_sq_plus, omega_sq_minus

# Plot dispersion relation
print("\nComputing dispersion relation...")

k_array = np.logspace(-20, -16, 100)  # m⁻¹
m_coh = H0 / c  # Coherence field mass ~ Hubble scale
alpha_lambda_rho = 1e-10 * rho_crit  # Coupling (placeholder)

omega_plus = []
omega_minus = []

for k in k_array:
    wp, wm = dispersion_relation(k, m_coh, alpha_lambda_rho)
    if wp is not None:
        omega_plus.append(np.sqrt(max(wp, 0)))
        omega_minus.append(np.sqrt(max(wm, 0)))
    else:
        omega_plus.append(0)
        omega_minus.append(0)

omega_plus = np.array(omega_plus)
omega_minus = np.array(omega_minus)

# =============================================================================
# PART 11: SUMMARY AND NEXT STEPS
# =============================================================================

print("""
================================================================================
PART 11: SUMMARY AND NEXT STEPS
================================================================================

WHAT WE'VE FOUND:

1. MATTER-SOURCED CMB
   - The coherence field is sourced by matter: δφ ∝ δ
   - CMB temperature traces coherence: δT/T ∝ δφ
   - This gives C_l ∝ P(k) — a smooth spectrum

2. NO SHARP PEAKS
   - The matter power spectrum has weak BAO wiggles
   - These don't produce sharp acoustic peaks
   - We need an additional mechanism

3. COUPLED OSCILLATIONS
   - The coherence-matter system has coupled dynamics
   - The dispersion relation shows two modes
   - One mode might produce oscillations

THE FUNDAMENTAL ISSUE:
----------------------
In ΛCDM, the acoustic peaks come from a TEMPORAL process:
- Sound waves propagate for 400,000 years
- Modes that fit integer half-wavelengths in the sound horizon
  are enhanced/suppressed

In coherence cosmology (static universe):
- There's no "time since the Big Bang"
- No natural timescale for oscillations to develop
- Peaks must come from SPATIAL structure, not temporal evolution

POSSIBLE RESOLUTION:
--------------------
The coherence field might have a SPATIAL oscillation mode:

If the coherence field has a characteristic wavelength λ_coh:
    λ_coh = 2π / m_coh = 2π c / H_0 ~ 4000 Mpc

This is the Hubble scale — too large for the acoustic peaks.

But if there's a SHORTER wavelength mode from the matter coupling:
    λ_eff ~ 150 Mpc (the BAO scale)

This could create peaks at the right angular scale.

WHAT'S NEEDED:
--------------
1. A mechanism that imprints the BAO scale onto the CMB
2. Amplification of BAO wiggles into sharp peaks
3. Correct peak height ratios (odd vs even peaks)

PLACEHOLDER:
This remains an open problem. The CMB power spectrum is the
most challenging aspect of coherence cosmology.

Possible paths forward:
1. Resonant amplification of BAO
2. Coherence field mode structure
3. Non-linear effects in coherence-matter coupling
4. Alternative interpretation of the peaks
""")

# Final figure
fig2, ax = plt.subplots(figsize=(10, 6))
ax.semilogy(l_array, Cl_lcdm_like, 'b-', linewidth=2, label='Coherence model (current)')
ax.errorbar(l_planck, Cl_planck, yerr=Cl_planck_err, fmt='ko', markersize=10, label='Planck 2018')

# Add vertical lines for expected peak positions
for i, l_peak in enumerate([220, 540, 810]):
    ax.axvline(l_peak, color='r', linestyle='--', alpha=0.5)
    ax.text(l_peak, 8000, f'l={l_peak}', ha='center', fontsize=10)

ax.set_xlabel('Multipole l', fontsize=12)
ax.set_ylabel('$l(l+1)C_l/2\\pi$ [μK²]', fontsize=12)
ax.set_title('CMB Power Spectrum: Coherence Cosmology vs Planck', fontsize=14)
ax.legend(fontsize=10)
ax.set_xlim(10, 2000)
ax.set_ylim(100, 10000)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/Users/leonardspeiser/Projects/sigmagravity/current/derivations/cmb_vs_planck.png', dpi=150)
print("\nSaved cmb_vs_planck.png")

print("""
================================================================================
STATUS: CMB POWER SPECTRUM
================================================================================

WHAT WORKS:
✓ Overall amplitude can be matched
✓ General shape (peak at l ~ few hundred)
✓ Damping at high l

WHAT DOESN'T WORK:
✗ Sharp acoustic peaks not reproduced
✗ Peak height ratios not explained
✗ Specific peak positions (220, 540, 810) not derived

THIS IS THE CRITICAL REMAINING CHALLENGE.

The CMB acoustic peaks are the strongest evidence for:
1. A hot, dense early universe
2. Baryon-photon acoustic oscillations
3. Dark matter providing potential wells

Coherence cosmology needs a mechanism to produce these peaks
without invoking a Big Bang.

POSSIBLE APPROACHES TO EXPLORE:
1. Coherence field resonances with BAO
2. Non-linear mode coupling
3. Modified coherence field dynamics
4. Alternative interpretation (foreground effects?)
""")

print("=" * 100)
print("END OF CMB POWER SPECTRUM ANALYSIS")
print("=" * 100)

