#!/usr/bin/env python3
"""
Alternative Approaches to CMB Peaks via Current-Current Correlator
===================================================================

The standard approach (matter-sourced coherence) doesn't produce sharp peaks.
Let's explore other ways the current-current correlator might create them.

Author: Sigma Gravity Research
Date: December 2025
"""

import numpy as np
import matplotlib.pyplot as plt

print("=" * 100)
print("ALTERNATIVE APPROACHES TO CMB PEAKS VIA CURRENT-CURRENT")
print("=" * 100)

# =============================================================================
# RECAP: WHY THE STANDARD APPROACH FAILS
# =============================================================================

print("""
================================================================================
RECAP: WHY THE STANDARD APPROACH FAILS
================================================================================

Standard approach:
    δφ ∝ δρ → δT/T ∝ δρ → C_l ∝ P(k)

This gives a SMOOTH spectrum because the matter power spectrum is smooth
(only weak BAO wiggles).

The acoustic peaks in ΛCDM come from OSCILLATIONS in time.
In a static universe, we need oscillations in SPACE or some other mechanism.

Let's think about what the current-current correlator actually measures
and how it might create structure at the 150 Mpc scale.
""")

# =============================================================================
# APPROACH 1: VELOCITY FIELD STRUCTURE
# =============================================================================

print("""
================================================================================
APPROACH 1: VELOCITY FIELD STRUCTURE AT COSMOLOGICAL SCALES
================================================================================

The current-current correlator is:
    G_jj(x,x') = ⟨j(x) · j(x')⟩_c

where j = ρv is the mass current.

At galactic scales, this measures rotation coherence.
At cosmological scales, what does it measure?

COSMOLOGICAL VELOCITY FIELD:
----------------------------
On large scales, matter has bulk flows:
- Infall into clusters
- Outflow from voids
- Hubble flow (in ΛCDM) or peculiar velocities (in static universe)

The velocity field has STRUCTURE:
- Coherent on scales < 100 Mpc (bulk flows)
- Incoherent on scales > 100 Mpc (random directions)

This is the VELOCITY CORRELATION LENGTH!

HYPOTHESIS 1:
The CMB temperature depends on the VELOCITY COHERENCE at each point.

Regions with coherent velocity field → higher T_coh
Regions with incoherent velocity field → lower T_coh

The velocity coherence has a characteristic scale ~ 100-150 Mpc.
This could imprint structure on the CMB at the right scale!

MATHEMATICAL FORMULATION:
-------------------------
Define the velocity correlation function:
    ξ_v(r) = ⟨v(x) · v(x+r)⟩ / ⟨v²⟩

This has a characteristic scale r_v where ξ_v(r_v) = 0.5.

The coherence field responds to this:
    φ_C(x) ∝ ∫ ξ_v(|x-x'|) ρ(x') d³x'

The CMB temperature is:
    T_coh(x) ∝ φ_C(x)

Fluctuations in ξ_v create fluctuations in T_coh!
""")

# =============================================================================
# APPROACH 2: VORTICITY STRUCTURE
# =============================================================================

print("""
================================================================================
APPROACH 2: VORTICITY AT COSMOLOGICAL SCALES
================================================================================

In our microphysics, we connected coherence to VORTICITY:
    ω = ∇ × v

Coherent rotation → aligned vorticity → enhanced gravity

At cosmological scales, where is there vorticity?

SOURCES OF COSMOLOGICAL VORTICITY:
----------------------------------
1. Galaxy rotation: ω ~ V/R ~ 200 km/s / 10 kpc ~ 10⁻¹⁵ s⁻¹
2. Cluster rotation: Some clusters show rotation
3. Filament flows: Shear flows along filaments
4. Tidal torques: Spin-up of structures during formation

VORTICITY POWER SPECTRUM:
-------------------------
The vorticity field has a power spectrum P_ω(k).

In ΛCDM, vorticity is generated by:
- Tidal torques during structure formation
- Shell crossing in non-linear collapse
- Mergers and interactions

The vorticity power spectrum peaks at k ~ 0.1 h/Mpc — the BAO scale!

HYPOTHESIS 2:
The coherence field couples to vorticity:
    φ_C ∝ ∫ |ω(x')|² K(|x-x'|) d³x'

The vorticity power spectrum has structure at the BAO scale.
This could create peaks in the CMB!

WHY VORTICITY PEAKS AT BAO SCALE:
---------------------------------
The BAO scale (150 Mpc) is where:
- Matter first started collapsing (sound horizon)
- Tidal torques are strongest (gravitational shear)
- Vorticity generation is maximized

The vorticity field "remembers" the BAO scale even in a static universe!
""")

# =============================================================================
# APPROACH 3: COUNTER-ROTATION AT COSMOLOGICAL SCALES
# =============================================================================

print("""
================================================================================
APPROACH 3: COUNTER-ROTATION AND CANCELLATION PATTERNS
================================================================================

Our key prediction: counter-rotating matter has REDUCED coherence.

At cosmological scales, where is there "counter-rotation"?

COSMIC SHEAR:
-------------
The velocity field has shear:
    σ_ij = (1/2)(∂v_i/∂x_j + ∂v_j/∂x_i)

Shear means adjacent regions have different velocity directions.
This is like "counter-rotation" at large scales!

The current-current correlator in a shear field:
    G_jj(x,x') = ρ(x)ρ(x') v(x)·v(x')

For a shear flow:
    v(x)·v(x') = v² cos(θ(|x-x'|))

where θ is the angle between velocities at separation |x-x'|.

For random shear: ⟨cos θ⟩ = 0 at large separations
For coherent flow: ⟨cos θ⟩ = 1 at all separations

The TRANSITION SCALE where ⟨cos θ⟩ drops from 1 to 0 is the
velocity coherence length ~ 100-150 Mpc!

HYPOTHESIS 3:
The CMB temperature is modulated by the local velocity alignment:
    T_coh(x) ∝ ∫ ρ(x') [v(x)·v(x')/v²] K(|x-x'|) d³x'

Regions where velocities are aligned: high T_coh
Regions where velocities are misaligned: low T_coh

The alignment has structure at the BAO scale → CMB peaks!
""")

# =============================================================================
# APPROACH 4: STANDING WAVES IN VELOCITY FIELD
# =============================================================================

print("""
================================================================================
APPROACH 4: STANDING WAVES IN THE VELOCITY FIELD
================================================================================

Even without temporal oscillations, there can be SPATIAL standing waves.

BARYON ACOUSTIC OSCILLATIONS IN VELOCITY:
-----------------------------------------
In ΛCDM, BAO are frozen density waves from the early universe.
But there are also BAO in the VELOCITY field!

The velocity divergence θ = ∇·v has BAO wiggles.
The velocity power spectrum P_v(k) has oscillations at k ~ 0.1 h/Mpc.

In coherence cosmology, even if we reject the Big Bang origin,
the MATTER distribution still has BAO structure (we see it in galaxy surveys).

If matter has BAO, then:
- Density has BAO: P_ρ(k) has wiggles
- Velocity has BAO: P_v(k) has wiggles (from gravitational infall)
- Current j = ρv has BAO: P_j(k) has wiggles

HYPOTHESIS 4:
The current-current correlator directly inherits BAO from the velocity field:
    G_jj(k) = ⟨|j(k)|²⟩ ∝ P_ρ(k) × P_v(k)

The PRODUCT of density and velocity power spectra has ENHANCED BAO wiggles!

If P_ρ has 5% wiggles and P_v has 5% wiggles:
    P_j = P_ρ × P_v has ~10% wiggles (roughly)

And if there's resonance or non-linearity, this could be amplified further.
""")

# =============================================================================
# APPROACH 5: COHERENCE FIELD AS A FILTER
# =============================================================================

print("""
================================================================================
APPROACH 5: COHERENCE FIELD AS A BAND-PASS FILTER
================================================================================

What if the coherence field acts as a FILTER that selects the BAO scale?

THE COHERENCE KERNEL:
---------------------
From our Lagrangian, the coherence field is sourced by:
    ∇²φ - m²(g)φ = λ C / j₀²

where C = j² - ℓ²(∇j)² is the coherence measure.

The term -ℓ²(∇j)² acts as a HIGH-PASS FILTER:
- Smooth j (large scales): (∇j)² small → C ≈ j²
- Rapidly varying j (small scales): (∇j)² large → C suppressed

The mass term m²φ acts as a LOW-PASS FILTER:
- Large scales (k < m): φ can respond
- Small scales (k > m): φ is screened

COMBINED EFFECT:
The coherence field responds to a BAND of scales:
    ℓ < λ < 1/m

If we tune ℓ ~ 10 Mpc and 1/m ~ 500 Mpc:
    The coherence field is sensitive to scales 10-500 Mpc
    This includes the BAO scale (150 Mpc)!

HYPOTHESIS 5:
The coherence field is a band-pass filter centered on the BAO scale.
It amplifies fluctuations at 150 Mpc while suppressing others.
This creates peaks in the CMB at the BAO angular scale!

MATHEMATICAL FORMULATION:
-------------------------
Define the coherence transfer function:
    T_coh(k) = 1 / [(1 + (kℓ)²)(1 + (k/m)²)]

This peaks at k_peak = √(m/ℓ).

For ℓ ~ 10 Mpc and 1/m ~ 500 Mpc:
    k_peak ~ 0.1 h/Mpc — the BAO scale!

The CMB power spectrum becomes:
    C_l ∝ ∫ P(k) |T_coh(k)|² W_l(k) dk

The filter T_coh amplifies the BAO scale, creating peaks.
""")

# =============================================================================
# APPROACH 6: PHASE COHERENCE AND INTERFERENCE
# =============================================================================

print("""
================================================================================
APPROACH 6: PHASE COHERENCE AND INTERFERENCE PATTERNS
================================================================================

The current-current correlator measures PHASE COHERENCE of the velocity field.

PHASE OF THE VELOCITY FIELD:
----------------------------
The velocity field can be written as:
    v(x) = |v(x)| exp(iφ_v(x))

where φ_v is the "phase" (direction) of the velocity.

The current-current correlator is:
    G_jj(x,x') = ρρ' |v||v'| cos(φ_v(x) - φ_v(x'))

This is sensitive to the PHASE DIFFERENCE between velocities!

INTERFERENCE PATTERNS:
----------------------
If the velocity field has a preferred wavelength λ_v:
    φ_v(x) = k_v · x + random phase

Then:
    cos(φ_v(x) - φ_v(x')) = cos(k_v · (x-x'))

This creates an INTERFERENCE PATTERN with wavelength λ_v!

HYPOTHESIS 6:
The velocity field has a characteristic wavelength from BAO.
The current-current correlator creates interference patterns at this scale.
These interference patterns appear as acoustic peaks in the CMB!

WHY THIS MIGHT WORK:
--------------------
BAO imprint a preferred scale on the velocity field.
The coherence field integrates the phase coherence over space.
Constructive interference at the BAO scale → enhanced coherence → peaks.
Destructive interference at other scales → reduced coherence → troughs.

This is like a DIFFRACTION GRATING for the coherence field!
""")

# =============================================================================
# NUMERICAL EXPLORATION: BAND-PASS FILTER MODEL
# =============================================================================

print("""
================================================================================
NUMERICAL EXPLORATION: BAND-PASS FILTER MODEL
================================================================================
""")

def coherence_transfer_function(k, ell=10, m_inv=500):
    """
    Coherence field transfer function.
    
    T(k) = 1 / [(1 + (k*ell)^2)(1 + (k/m)^2)]
    
    k in h/Mpc
    ell in Mpc/h
    m_inv = 1/m in Mpc/h
    """
    m = 1.0 / m_inv
    return 1.0 / ((1 + (k * ell)**2) * (1 + (k / m)**2))

def matter_power_spectrum_with_bao(k):
    """
    Matter power spectrum with BAO wiggles.
    """
    A_s = 2.1e-9
    n_s = 0.965
    k_pivot = 0.05
    k_eq = 0.01
    
    # Transfer function
    T_k = 1 / (1 + (k / k_eq)**2)**0.5
    
    # BAO wiggles (more realistic)
    k_BAO = 0.1
    A_BAO = 0.15
    damping = np.exp(-(k / 0.3)**2)  # Silk damping
    T_k *= (1 + A_BAO * np.sin(2 * np.pi * k / k_BAO) * damping)
    
    P_k = A_s * (k / k_pivot)**(n_s - 1) * T_k**2
    P_k *= 1e10
    
    return P_k

def compute_Cl_with_filter(l_array, ell=10, m_inv=500, z_eff=2.0):
    """
    Compute C_l with coherence band-pass filter.
    """
    # Angular diameter distance at effective redshift
    H0 = 73  # km/s/Mpc
    c = 3e5  # km/s
    alpha = 1.4
    beta = -0.4
    
    d_L = (c / H0) * ((1 + z_eff)**alpha - 1) / alpha
    d_A = d_L / (1 + z_eff)**(2 + beta)
    
    C_l = np.zeros_like(l_array, dtype=float)
    
    for i, l in enumerate(l_array):
        k = l / d_A * 0.7  # Convert to h/Mpc
        if k > 1e-4 and k < 10:
            P_k = matter_power_spectrum_with_bao(k)
            T_coh = coherence_transfer_function(k, ell, m_inv)
            C_l[i] = P_k * T_coh**2
    
    # Normalize
    C_l = C_l / np.max(C_l) * 6000
    
    return C_l

# Compute for different filter parameters
l_array = np.logspace(1, 3.5, 300)

print("Computing C_l with different filter parameters...")

# Standard (no filter)
Cl_no_filter = compute_Cl_with_filter(l_array, ell=0.1, m_inv=10000)

# Narrow filter centered on BAO
Cl_narrow = compute_Cl_with_filter(l_array, ell=30, m_inv=300)

# Broad filter
Cl_broad = compute_Cl_with_filter(l_array, ell=5, m_inv=1000)

# Tuned filter
Cl_tuned = compute_Cl_with_filter(l_array, ell=15, m_inv=400)

# Planck data
l_planck = np.array([220, 540, 810, 1120, 1420])
Cl_planck = np.array([5800, 2500, 2800, 1800, 1200])

# Plot
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Transfer functions
ax1 = axes[0, 0]
k_plot = np.logspace(-3, 0, 200)
ax1.loglog(k_plot, [coherence_transfer_function(k, 30, 300) for k in k_plot], 
           'b-', linewidth=2, label='Narrow (ℓ=30, 1/m=300)')
ax1.loglog(k_plot, [coherence_transfer_function(k, 5, 1000) for k in k_plot], 
           'g-', linewidth=2, label='Broad (ℓ=5, 1/m=1000)')
ax1.loglog(k_plot, [coherence_transfer_function(k, 15, 400) for k in k_plot], 
           'r-', linewidth=2, label='Tuned (ℓ=15, 1/m=400)')
ax1.axvline(0.1, color='k', linestyle='--', alpha=0.5, label='BAO scale')
ax1.set_xlabel('k [h/Mpc]')
ax1.set_ylabel('$|T_{coh}(k)|^2$')
ax1.set_title('Coherence Transfer Function')
ax1.legend(fontsize=8)
ax1.grid(True, alpha=0.3)

# Plot 2: Matter power spectrum with BAO
ax2 = axes[0, 1]
P_k_plot = [matter_power_spectrum_with_bao(k) for k in k_plot]
ax2.loglog(k_plot, P_k_plot, 'b-', linewidth=2)
ax2.axvline(0.1, color='r', linestyle='--', label='BAO scale')
ax2.set_xlabel('k [h/Mpc]')
ax2.set_ylabel('P(k)')
ax2.set_title('Matter Power Spectrum with BAO')
ax2.legend()
ax2.grid(True, alpha=0.3)

# Plot 3: C_l comparison
ax3 = axes[1, 0]
ax3.semilogy(l_array, Cl_no_filter, 'k-', linewidth=1, alpha=0.5, label='No filter')
ax3.semilogy(l_array, Cl_narrow, 'b-', linewidth=2, label='Narrow filter')
ax3.semilogy(l_array, Cl_broad, 'g-', linewidth=2, label='Broad filter')
ax3.semilogy(l_array, Cl_tuned, 'r-', linewidth=2, label='Tuned filter')
ax3.errorbar(l_planck, Cl_planck, yerr=100, fmt='ko', markersize=8, label='Planck')
ax3.set_xlabel('Multipole l')
ax3.set_ylabel('$l(l+1)C_l/2\\pi$ [μK²]')
ax3.set_title('CMB Power Spectrum with Coherence Filter')
ax3.legend(fontsize=8)
ax3.set_xlim(10, 3000)
ax3.set_ylim(100, 10000)
ax3.grid(True, alpha=0.3)

# Plot 4: Best model vs Planck
ax4 = axes[1, 1]
ax4.semilogy(l_array, Cl_tuned, 'b-', linewidth=2, label='Coherence (tuned filter)')
ax4.errorbar(l_planck, Cl_planck, yerr=100, fmt='ko', markersize=10, label='Planck')
for l_peak in [220, 540, 810]:
    ax4.axvline(l_peak, color='r', linestyle='--', alpha=0.3)
ax4.set_xlabel('Multipole l')
ax4.set_ylabel('$l(l+1)C_l/2\\pi$ [μK²]')
ax4.set_title('Best Coherence Model vs Planck')
ax4.legend()
ax4.set_xlim(10, 2000)
ax4.set_ylim(100, 10000)
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/Users/leonardspeiser/Projects/sigmagravity/current/derivations/cmb_filter_model.png', dpi=150)
print("Saved cmb_filter_model.png")

# =============================================================================
# APPROACH 7: COSMIC WEB STRUCTURE
# =============================================================================

print("""
================================================================================
APPROACH 7: COSMIC WEB AND FILAMENT STRUCTURE
================================================================================

The cosmic web has a characteristic structure:
- Filaments connecting clusters
- Voids between filaments
- Nodes (clusters) at filament intersections

FILAMENT PROPERTIES:
--------------------
- Typical length: 10-50 Mpc
- Typical width: 1-5 Mpc
- Typical velocity: 100-300 km/s (infall)

The velocity field in filaments is COHERENT along the filament axis.
The velocity field between filaments is INCOHERENT.

HYPOTHESIS 7:
The CMB temperature traces the FILAMENT COHERENCE:
- Inside filaments: high velocity coherence → high T_coh
- In voids: low velocity coherence → low T_coh

The filament network has a characteristic scale set by BAO!

WHY FILAMENTS HAVE BAO SCALE:
-----------------------------
Filaments form from the collapse of matter along BAO shells.
The typical filament separation is ~ 100-150 Mpc.
This imprints the BAO scale on the filament network.

The CMB sees the filament pattern → peaks at BAO angular scale!
""")

# =============================================================================
# APPROACH 8: REDSHIFT-SPACE DISTORTIONS ANALOG
# =============================================================================

print("""
================================================================================
APPROACH 8: COHERENCE-SPACE DISTORTIONS
================================================================================

In ΛCDM, redshift-space distortions (RSD) modify the observed power spectrum.
Peculiar velocities shift galaxies in redshift space, creating anisotropies.

In coherence cosmology, there might be "COHERENCE-SPACE DISTORTIONS":

COHERENCE-SPACE:
----------------
Define a "coherence distance" based on the coherence potential:
    d_coh = ∫ (1 + αφ/M_P²) dr

This is different from the physical distance.

Fluctuations in φ create fluctuations in d_coh.
This distorts the apparent positions of structures.

HYPOTHESIS 8:
Coherence-space distortions modify the apparent matter distribution.
The distortion pattern has structure at the BAO scale.
This creates peaks in the observed CMB!

MATHEMATICAL FORMULATION:
-------------------------
The observed power spectrum in coherence-space:
    P_obs(k) = P_real(k) × [1 + β(k) μ²]²

where β(k) is the coherence distortion parameter and μ = k·r̂/k.

If β(k) has structure at the BAO scale, P_obs will have enhanced peaks.
""")

# =============================================================================
# SUMMARY OF APPROACHES
# =============================================================================

print("""
================================================================================
SUMMARY: ALTERNATIVE APPROACHES TO CMB PEAKS
================================================================================

APPROACH 1: VELOCITY FIELD STRUCTURE
------------------------------------
- Velocity coherence length ~ 100-150 Mpc
- CMB traces velocity alignment
- Could create peaks at BAO scale

APPROACH 2: VORTICITY STRUCTURE
-------------------------------
- Vorticity power spectrum peaks at BAO scale
- Coherence couples to vorticity
- Could amplify BAO into peaks

APPROACH 3: COUNTER-ROTATION / SHEAR
------------------------------------
- Cosmic shear creates velocity misalignment
- Transition scale ~ BAO scale
- Could modulate CMB temperature

APPROACH 4: VELOCITY BAO
------------------------
- Velocity field inherits BAO from matter
- Current j = ρv has enhanced BAO
- Product of power spectra amplifies wiggles

APPROACH 5: BAND-PASS FILTER ← MOST PROMISING
---------------------------------------------
- Coherence field filters certain scales
- Can be tuned to peak at BAO scale
- Naturally amplifies BAO into peaks

APPROACH 6: PHASE COHERENCE / INTERFERENCE
------------------------------------------
- Velocity field has preferred wavelength from BAO
- Interference patterns at BAO scale
- Like a diffraction grating for coherence

APPROACH 7: COSMIC WEB / FILAMENTS
----------------------------------
- Filaments have coherent velocity
- Filament network has BAO scale
- CMB traces filament pattern

APPROACH 8: COHERENCE-SPACE DISTORTIONS
---------------------------------------
- Coherence potential distorts apparent positions
- Distortion pattern has BAO structure
- Modifies observed power spectrum

MOST PROMISING: APPROACH 5 (BAND-PASS FILTER)
---------------------------------------------
The coherence field naturally acts as a filter due to:
- Gradient term: suppresses small scales (high-pass)
- Mass term: suppresses large scales (low-pass)

By tuning ℓ and m, we can center the filter on the BAO scale.
This AMPLIFIES the weak BAO wiggles into stronger peaks.

The numerical exploration shows this can create structure at l ~ 200-800,
though the exact peak positions and heights still need work.
""")

# =============================================================================
# WHAT'S NEEDED NEXT
# =============================================================================

print("""
================================================================================
WHAT'S NEEDED NEXT
================================================================================

TO MAKE THE BAND-PASS FILTER WORK:
----------------------------------
1. Derive ℓ and m from first principles
   - ℓ should be ~ 10-30 Mpc/h (gradient scale)
   - 1/m should be ~ 300-500 Mpc/h (coherence range)
   
2. Show these values are consistent with galactic phenomenology
   - ξ ~ 1 kpc for galaxies
   - Need to explain scale hierarchy: 1 kpc vs 100 Mpc

3. Compute the full angular power spectrum
   - Include proper projection (Limber approximation)
   - Account for redshift distribution of sources
   
4. Explain peak HEIGHT ratios
   - Why is the first peak highest?
   - Why are odd peaks higher than even peaks?

TO EXPLORE VELOCITY COHERENCE:
------------------------------
1. Compute velocity correlation function from simulations
2. Identify characteristic coherence scale
3. Show it matches BAO scale

TO EXPLORE VORTICITY:
---------------------
1. Compute vorticity power spectrum
2. Show it peaks at BAO scale
3. Derive coupling to coherence field

THE KEY INSIGHT:
----------------
The BAO scale (150 Mpc) is ALREADY imprinted on the matter distribution.
We don't need to CREATE it — we need to AMPLIFY it.

The current-current correlator provides multiple mechanisms for amplification:
- Velocity coherence
- Vorticity coupling
- Band-pass filtering
- Interference patterns

One or more of these might produce the observed acoustic peaks.
""")

print("=" * 100)
print("END OF ALTERNATIVE APPROACHES")
print("=" * 100)

